# Generated by Django 6.0.2 on 2026-02-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hydra', '0015_alter_hydradistributionmode_description_and_more'),
        ('talos_reasoning', '0003_modelregistry_remove_reasoninggoal_parent_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalosEngramTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalosEngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('vector_id', models.UUIDField(blank=True, null=True)),
                ('heads', models.ManyToManyField(related_name='engram', to='hydra.hydrahead')),
                ('sessions', models.ManyToManyField(to='talos_reasoning.reasoningsession')),
                ('source_turns', models.ManyToManyField(to='talos_reasoning.reasoningturn')),
                ('tags', models.ManyToManyField(related_name='engram', to='talos_hippocampus.talosengramtag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
