# Generated by Django 6.0.2 on 2026-02-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0015_alter_hydradistributionmode_description_and_more'),
        ('talos_hippocampus', '0001_initial'),
        ('talos_reasoning', '0004_remove_toolcall_status_remove_toolcall_tool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talosengram',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='engram', to='hydra.hydrahead'),
        ),
        migrations.AlterField(
            model_name='talosengram',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='engram', to='talos_reasoning.reasoningsession'),
        ),
        migrations.AlterField(
            model_name='talosengram',
            name='source_turns',
            field=models.ManyToManyField(blank=True, related_name='engram', to='talos_reasoning.reasoningturn'),
        ),
        migrations.AlterField(
            model_name='talosengram',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='engram', to='talos_hippocampus.talosengramtag'),
        ),
    ]
