# Generated by Django 6.0.2 on 2026-02-21 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0015_alter_hydradistributionmode_description_and_more'),
        ('talos_hippocampus', '0003_delete_talosengram'),
        ('talos_reasoning', '0010_alter_reasoningsession_current_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalosEngram',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('vector_id', models.UUIDField(blank=True, null=True)),
                ('heads', models.ManyToManyField(blank=True, related_name='engram', to='hydra.hydrahead')),
                ('sessions', models.ManyToManyField(blank=True, related_name='engram', to='talos_reasoning.reasoningsession')),
                ('source_turns', models.ManyToManyField(blank=True, related_name='engram', to='talos_reasoning.reasoningturn')),
                ('tags', models.ManyToManyField(blank=True, related_name='engram', to='talos_hippocampus.talosengramtag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
