# Generated by Django 6.0.2 on 2026-02-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0012_remove_sessionconclusion_name_and_more'),
        ('hydra', '0016_rename_spell_log_hydrahead_application_log'),
        ('prefrontal_cortex', '0001_initial'),
        ('talos_hippocampus', '0006_talosengram_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='talosengram',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='prefrontal_cortex.pfctask'),
        ),
        migrations.AlterField(
            model_name='talosengram',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='hydra.hydrahead'),
        ),
        migrations.AlterField(
            model_name='talosengram',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='frontal_lobe.reasoningsession'),
        ),
        migrations.AlterField(
            model_name='talosengram',
            name='source_turns',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='frontal_lobe.reasoningturn'),
        ),
        migrations.AlterField(
            model_name='talosengram',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='talos_hippocampus.talosengramtag'),
        ),
    ]
