# Generated by Django 6.0.3 on 2026-04-14 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Executable',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal', models.BooleanField(default=False, help_text='Internal Python Function')),
                ('working_path', models.CharField(blank=True, help_text='[DEPRECATED/UNUSED] Where to run the executable.', max_length=500)),
                ('executable', models.CharField(help_text='Full path to the executable, including filename.', max_length=500)),
                ('log', models.CharField(blank=True, help_text='Full path to the log, including filename.', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutableArgument',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('argument', models.CharField(help_text='The argument itself.', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutableSwitch',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag', models.CharField(help_text="The actual flag e.g. '-clean', include equals or space if value is present.", max_length=255)),
                ('value', models.CharField(blank=True, help_text='The value of the flag, if any.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False, help_text='Only one environment can be selected at a time.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironmentContextKey',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironmentStatus',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironmentType',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutableArgumentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=10)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.executableargument')),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.executable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExecutableSupplementaryFileOrPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('path', models.CharField(help_text='Full path to the file.', max_length=500)),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.executable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='executable',
            name='switches',
            field=models.ManyToManyField(blank=True, to='environments.executableswitch'),
        ),
    ]
