# Generated by Django 6.0 on 2026-01-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalosExecutable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('internal', models.BooleanField(default=False, help_text='Internal Talos Python Function')),
                ('working_path', models.CharField(blank=True, help_text='Where to run the executable.', max_length=500)),
                ('executable', models.CharField(help_text='Full path to the executable, including filename.', max_length=500)),
                ('log', models.CharField(blank=True, help_text='Full path to the log, including filename.', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalosExecutableArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('argument', models.CharField(help_text='The argument itself.', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalosExecutableSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('flag', models.CharField(help_text="The actual flag e.g. '-clean', include equals or space if value is present.", max_length=255)),
                ('value', models.CharField(blank=True, help_text='The value of the flag, if any.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalosExecutableArgumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=10)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.talosexecutableargument')),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.talosexecutable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TalosExecutableSupplementaryFileOrPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('path', models.CharField(help_text='Full path to the file.', max_length=500)),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.talosexecutable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='talosexecutable',
            name='switches',
            field=models.ManyToManyField(blank=True, to='environments.talosexecutableswitch'),
        ),
    ]
