# Generated by Django 6.0 on 2026-01-05 22:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnvironment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Mike Desktop 2024', max_length=100, unique=True)),
                ('project_root', models.CharField(help_text='Path to .uproject folder', max_length=500)),
                ('engine_root', models.CharField(help_text='Path to UE_5.6 folder', max_length=500)),
                ('build_root', models.CharField(default='C:\\steambuild', help_text='Path to C:\\steambuild output', max_length=500)),
                ('project_name', models.CharField(default='TalosProject', max_length=100)),
                ('staging_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_port', models.IntegerField(default=5005)),
                ('is_active', models.BooleanField(default=False, help_text='Only one environment should be active at a time.')),
            ],
        ),
    ]
