# Generated by Django 6.0 on 2026-02-10 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnvironment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironmentContextVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('key', models.CharField(max_length=254)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironmentContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='environments.projectenvironment')),
                ('context_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.projectenvironmentcontextvariable')),
            ],
        ),
        migrations.AddField(
            model_name='projectenvironment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironmentstatus'),
        ),
        migrations.AddField(
            model_name='projectenvironment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironmenttype'),
        ),
    ]
