# Generated by Django 6.0.2 on 2026-03-01 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('temporal_lobe', '0002_rename_phase_iterationshift_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenvironment',
            name='default_iteration_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='temporal_lobe.iterationdefinition'),
        ),
    ]
