# Generated by Django 6.0 on 2026-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvironment',
            name='project_name',
            field=models.CharField(default='HSHVacancy', max_length=100),
        ),
    ]
