# Generated by Django 6.0.3 on 2026-04-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('temporal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenvironment',
            name='default_iteration_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='temporal_lobe.iterationdefinition'),
        ),
        migrations.AddField(
            model_name='contextvariable',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='environments.projectenvironment'),
        ),
        migrations.AddField(
            model_name='contextvariable',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.projectenvironmentcontextkey'),
        ),
        migrations.AddField(
            model_name='projectenvironment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironmentstatus'),
        ),
        migrations.AddField(
            model_name='projectenvironment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironmenttype'),
        ),
    ]
