# Generated by Django 6.0 on 2026-01-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_alter_projectenvironment_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvironment',
            name='agent_port',
            field=models.IntegerField(default=5005, help_text='Port the agent is listening on'),
        ),
        migrations.AlterField(
            model_name='projectenvironment',
            name='build_root',
            field=models.CharField(help_text='Path to BUILD output', max_length=500),
        ),
        migrations.AlterField(
            model_name='projectenvironment',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one build environment can be active at a time.'),
        ),
        migrations.AlterField(
            model_name='projectenvironment',
            name='project_name',
            field=models.CharField(help_text='The EXE Prefix (e.g., HSHVacancy)', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectenvironment',
            name='staging_dir',
            field=models.CharField(blank=True, help_text='Path to Staging output', max_length=500, null=True),
        ),
    ]
