# Generated by Django 6.0 on 2026-02-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_projectenvironment_projectenvironmentcontextvariable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenvironment',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectenvironment',
            name='selected',
            field=models.BooleanField(default=False, help_text='Only one environment can be selected at a time.'),
        ),
    ]
