# Generated by Django 6.0.2 on 2026-04-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_rename_talos_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executable',
            name='internal',
            field=models.BooleanField(default=False, help_text='Internal Python Function'),
        ),
    ]
