# Generated by Django 6.0.3 on 2026-04-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_executable_genome_executableargument_genome_and_more'),
        ('temporal_lobe', '0002_iterationdefinition_genome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvironment',
            name='default_iteration_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='temporal_lobe.iterationdefinition'),
        ),
    ]
