# Generated by Django 6.0 on 2026-01-21 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_alter_projectenvironment_agent_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalosExecutable',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('working_path', models.CharField(help_text='Where to run the executable.', max_length=500)),
                ('executable', models.CharField(help_text='Full path to the executable, including filename.', max_length=500)),
                ('log', models.CharField(help_text='Full path to the log, including filename.', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalosExecutableSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('flag', models.CharField(help_text="The actual flag e.g. '-clean', include equals or space if value is present.", max_length=100)),
                ('value', models.CharField(blank=True, help_text='The value of the flag, if any.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalosExecutableSupplementaryFileOrPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('path', models.CharField(help_text='Full path to the file.', max_length=500)),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.talosexecutable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='talosexecutable',
            name='switches',
            field=models.ManyToManyField(blank=True, to='environments.talosexecutableswitch'),
        ),
    ]
