# Generated by Django 6.0 on 2026-02-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_projectenvironment_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnvironmentContextKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='projectenvironmentcontext',
            name='context_variable',
        ),
        migrations.RemoveField(
            model_name='projectenvironmentcontext',
            name='environment',
        ),
        migrations.CreateModel(
            name='ContextVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='environments.projectenvironment')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.projectenvironmentcontextkey')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectEnvironmentContextVariable',
        ),
        migrations.DeleteModel(
            name='ProjectEnvironmentContext',
        ),
    ]
