# Generated by Django 6.0 on 2026-02-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_projectenvironmentcontextkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talosexecutable',
            name='working_path',
            field=models.CharField(blank=True, help_text='[DEPRECATED/UNUSED] Where to run the executable.', max_length=500),
        ),
    ]
