# Generated by Django 6.0.3 on 2026-04-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_alter_projectenvironment_default_iteration_definition'),
        ('temporal_lobe', '0002_iterationdefinition_genome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvironment',
            name='default_iteration_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationdefinition'),
        ),
    ]
