# Generated by Django 6.0 on 2026-01-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_talosexecutable_talosexecutableswitch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talosexecutable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
