# Generated by Django 6.0.3 on 2026-04-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_alter_projectenvironment_default_iteration_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectenvironment',
            name='type',
        ),
        migrations.DeleteModel(
            name='ProjectEnvironmentType',
        ),
    ]
