# Generated by Django 6.0 on 2026-01-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_alter_talosexecutable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talosexecutableswitch',
            name='flag',
            field=models.CharField(help_text="The actual flag e.g. '-clean', include equals or space if value is present.", max_length=255),
        ),
    ]
