# Generated by Django 6.0 on 2026-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_alter_talosexecutable_working_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvironment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talosexecutable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
