# Generated by Django 6.0 on 2026-01-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0006_alter_talosexecutableswitch_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalosExecutableArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('argument', models.CharField(help_text='The argument itself.', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalosExecutableArgumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=10)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.talosexecutableargument')),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.talosexecutable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
