# Generated by Django 6.0 on 2026-01-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0007_talosexecutableargument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talosexecutable',
            name='log',
            field=models.CharField(blank=True, help_text='Full path to the log, including filename.', max_length=500),
        ),
        migrations.AlterField(
            model_name='talosexecutable',
            name='working_path',
            field=models.CharField(blank=True, help_text='Where to run the executable.', max_length=500),
        ),
    ]
