# Generated by Django 6.0 on 2026-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0008_alter_talosexecutable_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talosexecutable',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
