# Generated by Django 6.0 on 2026-01-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0009_talosexecutable_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talosexecutable',
            name='internal',
            field=models.BooleanField(default=False, help_text='Internal Talos Python Function'),
        ),
    ]
