# Generated by Django 6.0 on 2026-01-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_buildjob_stage_and_more'),
        ('environments', '0010_alter_talosexecutable_internal'),
        ('hydra', '0020_remove_hydraspawn_environment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectEnvironment',
        ),
    ]
