services:
  # 1. The Database (With Vector Hardware)
  db:
    image: pgvector/pgvector:pg16
    container_name: are_self_db
    restart: always
    environment:
      POSTGRES_DB: postgres_talos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Wingsofbronze223
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The Nervous System (Task Queue)
  redis:
    image: redis
    container_name: are_self_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:

