# Generated by Django 6.0 on 2026-01-05 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order_index', models.FloatField(help_text='Order in the UI (e.g. 0.5, 1.0)')),
                ('script_filename', models.CharField(help_text='Filename in core/builder_engine/', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('timeout_seconds', models.IntegerField(default=300)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Mike Desktop 2024', max_length=100, unique=True)),
                ('project_root', models.CharField(help_text='Path to .uproject folder', max_length=500)),
                ('engine_root', models.CharField(help_text='Path to UE_5.6 folder', max_length=500)),
                ('build_root', models.CharField(help_text='Path to C:\\steambuild output', max_length=500)),
                ('staging_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_port', models.IntegerField(default=5005)),
                ('is_active', models.BooleanField(default=False, help_text='Only one environment should be active at a time.')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('unc_path', models.CharField(help_text='Network share path e.g. \\\\DREWDESK01\\steambuild', max_length=500)),
                ('agent_port', models.IntegerField(default=5005)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy'), ('STORAGE_ERROR', 'Storage Error')], default='OFFLINE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='core.buildjob')),
            ],
        ),
        migrations.AddField(
            model_name='buildjob',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipelinestage'),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='target_environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projectenvironment'),
        ),
    ]
