# Generated by Django 6.0 on 2026-01-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotetarget',
            name='is_exe_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remotetarget',
            name='remote_build_path',
            field=models.CharField(blank=True, help_text='Configured build root on the agent', max_length=500),
        ),
        migrations.AddField(
            model_name='remotetarget',
            name='remote_exe_path',
            field=models.CharField(blank=True, help_text='Located .exe path for launching', max_length=500),
        ),
        migrations.AddField(
            model_name='remotetarget',
            name='remote_log_path',
            field=models.CharField(blank=True, help_text='Configured project log path', max_length=500),
        ),
    ]
