# Generated by Django 6.0 on 2026-01-05 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remotetarget_is_exe_available_and_more'),
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildjob',
            name='target_environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.projectenvironment'),
        ),
        migrations.AddField(
            model_name='remotetarget',
            name='version',
            field=models.CharField(blank=True, help_text='Reported agent version', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectEnvironment',
        ),
    ]
