# Generated by Django 6.0 on 2026-01-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_buildjob_target_environment_and_more'),
        ('hydra', '0020_remove_hydraspawn_environment_and_more'),
        ('talos_agent', '0003_talosagentregistry_talosagentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildjob',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='buildjob',
            name='target_environment',
        ),
        migrations.RemoveField(
            model_name='joblog',
            name='job',
        ),
        migrations.DeleteModel(
            name='RemoteTarget',
        ),
        migrations.DeleteModel(
            name='PipelineStage',
        ),
        migrations.DeleteModel(
            name='BuildJob',
        ),
        migrations.DeleteModel(
            name='JobLog',
        ),
    ]
