# Generated by Django 6.0.2 on 2026-04-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaysessionstatus',
            name='name',
            field=models.CharField(db_index=True, max_length=254, unique=True),
        ),
    ]
