# Generated by Django 6.0.4 on 2026-04-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talos_gateway', '0002_alter_gatewaysessionstatus_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatewaysessionstatus',
            options={},
        ),
    ]
