# Generated by Django 6.0.4 on 2026-04-25 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talos_gateway', '0003_alter_gatewaysessionstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatewaysessionstatus',
            options={'verbose_name_plural': 'Gateway session statuses'},
        ),
    ]
