# Generated by Django 6.0.2 on 2026-03-23 00:20

import datetime
import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontal_lobe', '0001_initial'),
        ('hippocampus', '0001_initial'),
        ('hypothalamus', '0001_initial'),
        ('parietal_lobe', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='IdentityAddonPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('max_input_cost_per_token', models.DecimalField(decimal_places=15, default=0.0, help_text='Max Input Cost Per 1 Token. Set to 0.0 for strict Free only. (e.g., 0.00003 for GPT-4 level)', max_digits=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('function_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.identityaddonphase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityDisc',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_prompt_template', models.TextField(blank=True, help_text='The core instructions given to the Frontal Lobe.', null=True)),
                ('available', models.BooleanField(default=True)),
                ('last_message_to_self', models.TextField(blank=True, default='')),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('successes', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('addons', models.ManyToManyField(blank=True, to='identity.identityaddon')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.identitybudget')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelcategory')),
                ('enabled_tools', models.ManyToManyField(blank=True, to='parietal_lobe.tooldefinition')),
                ('last_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontal_lobe.reasoningturn')),
                ('memories', models.ManyToManyField(blank=True, to='hippocampus.talosengram')),
                ('tags', models.ManyToManyField(blank=True, to='identity.identitytag')),
                ('identity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.identitytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_prompt_template', models.TextField(blank=True, help_text='The core instructions given to the Frontal Lobe.', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelcategory')),
                ('enabled_tools', models.ManyToManyField(blank=True, to='parietal_lobe.tooldefinition')),
                ('addons', models.ManyToManyField(blank=True, to='identity.identityaddon')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.identitybudget')),
                ('tags', models.ManyToManyField(blank=True, to='identity.identitytag')),
                ('identity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.identitytype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
