# Generated by Django 6.0.3 on 2026-04-17 14:09

import datetime
import django.db.models.deletion
import pgvector.django.vector
import uuid
from decimal import Decimal
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontal_lobe', '0001_initial'),
        ('hippocampus', '0001_initial'),
        ('hypothalamus', '0001_initial'),
        ('parietal_lobe', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('duration', models.DurationField(blank=True, help_text='Reset interval. Null = lifetime, never resets.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityAddonPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('function_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('addon_class_name', models.CharField(blank=True, max_length=254, null=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.identityaddonphase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('max_input_cost_per_token', models.DecimalField(decimal_places=15, default=Decimal('0'), help_text='Candidate models with higher input cost are excluded entirely.', max_digits=25)),
                ('max_output_cost_per_token', models.DecimalField(decimal_places=15, default=Decimal('0'), help_text='Candidate models with higher output cost are excluded entirely.', max_digits=25)),
                ('max_spend_per_period', models.DecimalField(blank=True, decimal_places=15, help_text='Hard ceiling on total spend within the budget period. Null = unlimited.', max_digits=25, null=True)),
                ('max_spend_per_request', models.DecimalField(blank=True, decimal_places=15, help_text='Single-request cost ceiling. Null = unlimited.', max_digits=25, null=True)),
                ('warn_at_percent', models.PositiveSmallIntegerField(default=80, help_text='Emit a warning signal when spend reaches this % of max_spend_per_period.')),
                ('period', models.ForeignKey(blank=True, help_text='How often spend counters reset. Null = lifetime.', null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.budgetperiod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityDisc',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_prompt_template', models.TextField(blank=True, help_text='The core instructions given to the Frontal Lobe.', null=True)),
                ('available', models.BooleanField(default=True)),
                ('last_message_to_self', models.TextField(blank=True, default='')),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('successes', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('addons', models.ManyToManyField(blank=True, to='identity.identityaddon')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelcategory')),
                ('enabled_tools', models.ManyToManyField(blank=True, to='parietal_lobe.tooldefinition')),
                ('last_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontal_lobe.reasoningturn')),
                ('memories', models.ManyToManyField(blank=True, to='hippocampus.engram')),
                ('selection_filter', models.ForeignKey(blank=True, help_text='Scope this budget to a specific filter. Null = applies globally.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelselectionfilter')),
                ('tags', models.ManyToManyField(blank=True, to='identity.identitytag')),
                ('identity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.identitytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityDiscVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embeddings', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('identity_disc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_node', to='identity.identitydisc')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_prompt_template', models.TextField(blank=True, help_text='The core instructions given to the Frontal Lobe.', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelcategory')),
                ('enabled_tools', models.ManyToManyField(blank=True, to='parietal_lobe.tooldefinition')),
                ('selection_filter', models.ForeignKey(blank=True, help_text='Scope this budget to a specific filter. Null = applies globally.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelselectionfilter')),
                ('addons', models.ManyToManyField(blank=True, to='identity.identityaddon')),
                ('tags', models.ManyToManyField(blank=True, to='identity.identitytag')),
                ('identity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.identitytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityBudgetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('period_spend_start', models.DateTimeField(blank=True, help_text='When the current period started. Used to compute rolling spend against AIModelProviderUsageRecord.', null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='identity.identitybudget')),
                ('selection_filter', models.ForeignKey(blank=True, help_text='Scope this budget to a specific filter. Null = applies globally.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_assignments', to='hypothalamus.aimodelselectionfilter')),
                ('identity_disc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_assignments', to='identity.identitydisc')),
            ],
            options={
                'verbose_name': 'Identity Budget Assignment',
                'verbose_name_plural': 'Identity Budget Assignments',
                'unique_together': {('identity_disc', 'selection_filter', 'is_active')},
            },
        ),
    ]
