# Generated by Django 6.0.2 on 2026-03-09 21:25

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontal_lobe', '0001_initial'),
        ('hippocampus', '0001_initial'),
        ('parietal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('function_slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_prompt_template', models.TextField(help_text='The core instructions given to the Frontal Lobe.')),
                ('enabled_tools', models.ManyToManyField(blank=True, to='parietal_lobe.tooldefinition')),
                ('addons', models.ManyToManyField(blank=True, to='identity.identityaddon')),
                ('tags', models.ManyToManyField(blank=True, to='identity.identitytag')),
                ('identity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.identitytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityDisc',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('last_message_to_self', models.TextField(blank=True, default='')),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('successes', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.identity')),
                ('last_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontal_lobe.reasoningturn')),
                ('memories', models.ManyToManyField(blank=True, to='hippocampus.talosengram')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
