# Generated by Django 6.0.2 on 2026-03-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitydisc',
            name='identity',
        ),
    ]
