# Generated by Django 6.0.2 on 2026-03-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityaddon',
            name='function_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
