# Generated by Django 6.0.2 on 2026-03-26 12:36

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0012_failoverstrategy_failovertype_aimodelselectionfilter_and_more'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('duration', models.DurationField(blank=True, help_text='Reset interval. Null = lifetime, never resets.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='identitybudget',
            name='max_output_cost_per_token',
            field=models.DecimalField(decimal_places=15, default=Decimal('0'), help_text='Candidate models with higher output cost are excluded entirely.', max_digits=25),
        ),
        migrations.AddField(
            model_name='identitybudget',
            name='max_spend_per_period',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Hard ceiling on total spend within the budget period. Null = unlimited.', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='identitybudget',
            name='max_spend_per_request',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Single-request cost ceiling. Null = unlimited.', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='identitybudget',
            name='warn_at_percent',
            field=models.PositiveSmallIntegerField(default=80, help_text='Emit a warning signal when spend reaches this % of max_spend_per_period.'),
        ),
        migrations.AlterField(
            model_name='identitybudget',
            name='max_input_cost_per_token',
            field=models.DecimalField(decimal_places=15, default=Decimal('0'), help_text='Candidate models with higher input cost are excluded entirely.', max_digits=25),
        ),
        migrations.AddField(
            model_name='identitybudget',
            name='period',
            field=models.ForeignKey(blank=True, help_text='How often spend counters reset. Null = lifetime.', null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.budgetperiod'),
        ),
        migrations.CreateModel(
            name='IdentityBudgetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('period_spend_start', models.DateTimeField(blank=True, help_text='When the current period started. Used to compute rolling spend against AIModelProviderUsageRecord.', null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='identity.identitybudget')),
                ('identity_disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_assignments', to='identity.identitydisc')),
                ('selection_filter', models.ForeignKey(blank=True, help_text='Scope this budget to a specific filter. Null = applies globally.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_assignments', to='hypothalamus.aimodelselectionfilter')),
            ],
            options={
                'verbose_name': 'Identity Budget Assignment',
                'verbose_name_plural': 'Identity Budget Assignments',
                'unique_together': {('identity_disc', 'selection_filter', 'is_active')},
            },
        ),
    ]
