# Generated by Django 6.0.2 on 2026-03-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_budgetperiod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='identitydisc',
            name='budget',
        ),
    ]
