# Generated by Django 6.0.2 on 2026-03-13 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0005_remove_reasoningturn_turn_goals_delete_reasoninggoal'),
        ('identity', '0002_remove_identitydisc_identity'),
        ('parietal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='ai_models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontal_lobe.modelregistry'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='addons',
            field=models.ManyToManyField(blank=True, to='identity.identityaddon'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='ai_models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontal_lobe.modelregistry'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='enabled_tools',
            field=models.ManyToManyField(blank=True, to='parietal_lobe.tooldefinition'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='identity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.identitytype'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='system_prompt_template',
            field=models.TextField(blank=True, help_text='The core instructions given to the Frontal Lobe.', null=True),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='tags',
            field=models.ManyToManyField(blank=True, to='identity.identitytag'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='system_prompt_template',
            field=models.TextField(blank=True, help_text='The core instructions given to the Frontal Lobe.', null=True),
        ),
    ]
