# Generated by Django 6.0.3 on 2026-04-26 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_identity_genome_identityaddon_genome_and_more'),
        ('neuroplasticity', '0004_stamp_canonical_genome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AlterField(
            model_name='identityaddon',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AlterField(
            model_name='identitydisc',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
    ]
