# Generated by Django 6.0.3 on 2026-05-01 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_identity_genome_alter_identityaddon_genome_and_more'),
        ('neuroplasticity', '0005_neuralmodifier_selected_for_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarSelectedDisplayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(blank=True, max_length=254, null=True)),
                ('stored_filename', models.CharField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('emoji', models.CharField(blank=True, max_length=254, null=True)),
                ('tint_color', models.CharField(blank=True, max_length=254, null=True)),
                ('genome', models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier')),
                ('display', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='identity.avatarselecteddisplaytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='identity',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.avatar'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.avatar'),
        ),
    ]
