# Generated by Django 6.0.2 on 2026-03-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_identity_ai_models_identitydisc_addons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='ai_models',
            new_name='ai_model',
        ),
        migrations.RenameField(
            model_name='identitydisc',
            old_name='ai_models',
            new_name='ai_model',
        ),
    ]
