# Generated by Django 6.0.2 on 2026-03-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_remove_identity_budget_remove_identitydisc_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitybudgetassignment',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='identity.identitybudget'),
        ),
    ]
