# Generated by Django 6.0.2 on 2026-03-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_identitybudgetassignment_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitybudgetassignment',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='identity.identitybudget'),
        ),
        migrations.AlterField(
            model_name='identitybudgetassignment',
            name='identity_disc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_assignments', to='identity.identitydisc'),
        ),
    ]
