# Generated by Django 6.0.2 on 2026-03-26 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0012_failoverstrategy_failovertype_aimodelselectionfilter_and_more'),
        ('identity', '0005_alter_identitybudgetassignment_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='selection_filter',
            field=models.ForeignKey(blank=True, help_text='Scope this budget to a specific filter. Null = applies globally.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelselectionfilter'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='selection_filter',
            field=models.ForeignKey(blank=True, help_text='Scope this budget to a specific filter. Null = applies globally.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelselectionfilter'),
        ),
    ]
