# Generated by Django 6.0.2 on 2026-03-20 12:59

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0001_initial'),
        ('identity', '0005_identityaddonphase_identityaddon_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('max_input_cost_per_token', models.DecimalField(decimal_places=15, default=0.0, help_text='Max Input Cost Per 1 Token. Set to 0.0 for strict Free only. (e.g., 0.00003 for GPT-4 level)', max_digits=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='identity',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='identitydisc',
            name='ai_model',
        ),
        migrations.AddField(
            model_name='identity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelcategory'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelcategory'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.identitybudget'),
        ),
        migrations.AddField(
            model_name='identitydisc',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.identitybudget'),
        ),
    ]
