ABORTED_LABEL = 'Aborted'
CREATED_LABEL = 'Created'
PENDING_LABEL = 'Pending'
RUNNING_LABEL = 'Running'
SUCCESS_LABEL = 'Success'
FAILED_LABEL = 'Failed'
STOPPING_LABEL = 'Stopping'
STOPPED_LABEL = 'Stopped'
COPY_COMMAND = 'COPY'
COPY_LABEL = 'Copy'
MOVE_COMMAND = 'MOVE'
MOVE_LABEL = 'Move'
VALIDATE_EXISTS_COMMAND = 'VALIDATE_EXISTS'
VALIDATE_EXISTS_LABEL = 'Validate Exists'
DELETE_COMMAND = 'DELETE'
DELETE_LABEL = 'Delete'
DELEGATED_LABEL = 'Delegated'
IS_ALIVE_LABEL = 'Is Alive'
IS_TERMINAL_LABEL = 'Is Terminal'

KEY_SPIKE_ID = 'spike_id'
KEY_SPIKE_TRAIN_ID = 'spike_train_id'
KEY_EFFECTOR_ID = 'effector_id'
KEY_PATHWAY_ID = 'pathway_id'
KEY_PROVENANCE_ID = 'provenance_id'
KEY_SERVER = 'server'
KEY_ENVIRONMENT_ID = 'environment_id'

PROVENANCE_FIELD_NAME = 'provenance'

APPLICATION_LOG_FIELD_NAME = 'application_log'
EXECUTION_LOG_FIELD_NAME = 'execution_log'
RESULT_CODE_FIELD_NAME = 'result_code'

ENVIRONMENT_KEY = 'environment'
ENVIRONMENT_LABEL = 'Environment'

# --- Graph Editor Constants (Added) ---
KEY_ID = 'id'
KEY_TITLE = 'title'
KEY_X = 'x'
KEY_Y = 'y'
KEY_IS_ROOT = 'is_root'

TYPE_FLOW_STR = 'flow'
TYPE_SUCCESS_STR = 'success'
TYPE_FAIL_STR = 'fail'

VAL_UNKNOWN = 'Unknown'
VAL_PENDING = 'Pending...'
VAL_CMD_NOT_CAPTURED = 'Command not captured.'

HEAD_FIELD_NAME = 'spike'
NEURON_FIELD_NAME = 'neuron'
SPAWN_FIELD_NAME = 'spike_train'
SPELLBOOK_FIELD_NAME = 'pathway'
