# Generated by Django 6.0.2 on 2026-03-09 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NerveTerminalRegistry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=5005)),
                ('version', models.CharField(blank=True, help_text='Reported agent version', max_length=20, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NerveTerminalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NerveTerminalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('LAUNCH', 'Started Process'), ('KILL', 'Stopped Process'), ('CRASH', 'Detected Crash'), ('DISCONNECT', 'Lost Connection'), ('RECONNECT', 'Restored Connection'), ('UPDATE', 'Agent Code Updated')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='peripheral_nervous_system.nerveterminalregistry')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='nerveterminalregistry',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peripheral_nervous_system.nerveterminalstatus'),
        ),
        migrations.CreateModel(
            name='NerveTerminalTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage_mb', models.FloatField(default=0.0)),
                ('is_functioning', models.BooleanField(default=False)),
                ('is_alive', models.BooleanField(default=False)),
                ('storage_ok', models.BooleanField(default=False)),
                ('storage_info', models.CharField(blank=True, max_length=500)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='peripheral_nervous_system.nerveterminalregistry')),
            ],
            options={
                'verbose_name_plural': 'Agent Telemetry',
                'ordering': ['-timestamp'],
            },
        ),
    ]
