# Generated by Django 6.0 on 2026-01-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_reasoning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooldefinition',
            name='parameters_schema',
            field=models.TextField(blank=True, default=dict, help_text='JSON schema for tool parameters.'),
        ),
    ]
