# Generated by Django 6.0.2 on 2026-02-19 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_reasoning', '0004_remove_toolcall_status_remove_toolcall_tool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasoninggoal',
            name='delta',
        ),
        migrations.AddField(
            model_name='reasoningsession',
            name='delta',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='delta',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
