# Generated by Django 6.0.2 on 2026-02-19 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0015_alter_hydradistributionmode_description_and_more'),
        ('talos_reasoning', '0006_remove_reasoningsession_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasoningsession',
            name='node',
        ),
        migrations.RemoveField(
            model_name='reasoningsession',
            name='spawn_link',
        ),
        migrations.AddField(
            model_name='reasoningsession',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasoning_session', to='hydra.hydrahead'),
        ),
    ]
