# Generated by Django 6.0.2 on 2026-02-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_reasoning', '0008_remove_reasoningturn_active_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoningsession',
            name='current_focus',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='reasoningsession',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
