# Generated by Django 6.0.2 on 2026-02-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_reasoning', '0009_reasoningsession_current_focus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoningsession',
            name='current_focus',
            field=models.IntegerField(default=5),
        ),
    ]
