# Generated by Django 6.0.2 on 2026-02-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_reasoning', '0010_alter_reasoningsession_current_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoningturn',
            name='last_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talos_reasoning.reasoningturn'),
        ),
    ]
