# Generated by Django 6.0 on 2026-01-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hydra', '0009_remove_hydraspellbook_outcomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsciousStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('current_thought', models.TextField(help_text='The internal monologue or analysis result')),
                ('status', models.CharField(choices=[('THINKING', 'Thinking'), ('WAITING', 'Waiting'), ('DONE', 'Done')], default='THINKING', max_length=20)),
                ('spawn_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='hydra.hydraspawn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
