# Generated by Django 6.0 on 2026-01-30 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hydra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsciousStatus',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Conscious Statuses',
            },
        ),
        migrations.CreateModel(
            name='SystemDirectiveIdentifier',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'System Directive Identifiers',
            },
        ),
        migrations.CreateModel(
            name='ConsciousStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('current_thought', models.TextField(help_text='The internal monologue or analysis result')),
                ('used_prompt', models.TextField(blank=True, default='', help_text='The exact prompt sent to the model.')),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('model_name', models.CharField(blank=True, default='', max_length=50)),
                ('head_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thoughts', to='hydra.hydrahead')),
                ('spawn_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='hydra.hydraspawn')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='talos_frontal.consciousstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemDirective',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.TextField()),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('context_window_size', models.IntegerField(default=128000, help_text='Max context window (e.g. 4096, 8192, 128k)')),
                ('max_output_tokens', models.IntegerField(default=1024, help_text='Limit response length')),
                ('temperature', models.FloatField(default=0.1, help_text='Creativity (0.0 - 1.0)')),
                ('identifier', models.ForeignKey(help_text='The functional type of this directive.', on_delete=django.db.models.deletion.PROTECT, to='talos_frontal.systemdirectiveidentifier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
