# Generated by Django 6.0.2 on 2026-02-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talos_frontal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consciousstream',
            name='status',
        ),
        migrations.RemoveField(
            model_name='consciousstream',
            name='head_link',
        ),
        migrations.RemoveField(
            model_name='consciousstream',
            name='spawn_link',
        ),
        migrations.RemoveField(
            model_name='systemdirective',
            name='identifier',
        ),
        migrations.DeleteModel(
            name='ConsciousStatus',
        ),
        migrations.DeleteModel(
            name='ConsciousStream',
        ),
        migrations.DeleteModel(
            name='SystemDirective',
        ),
        migrations.DeleteModel(
            name='SystemDirectiveIdentifier',
        ),
    ]
