# Generated by Django 6.0 on 2026-01-11 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_frontal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsciousStatus',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Conscious Statuses',
            },
        ),
        migrations.AlterField(
            model_name='consciousstream',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='talos_frontal.consciousstatus'),
        ),
    ]
