# Generated by Django 6.0 on 2026-01-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0009_remove_hydraspellbook_outcomes'),
        ('talos_frontal', '0003_seed_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='consciousstream',
            name='head_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thoughts', to='hydra.hydrahead'),
        ),
    ]
