# Generated by Django 6.0 on 2026-01-11 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_frontal', '0004_consciousstream_head_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDirective',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text="Stable key for code lookups (e.g. 'analysis_core')", max_length=100, unique=True)),
                ('template', models.TextField(help_text='The prompt text. Use {variable} for dynamic injection.')),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
