# Generated by Django 6.0 on 2026-01-11 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_frontal', '0005_systemdirective'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDirectiveIdentifier',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'System Directive Identifiers',
            },
        ),
        migrations.AlterField(
            model_name='systemdirective',
            name='template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='systemdirective',
            name='identifier',
            field=models.ForeignKey(help_text='The functional type of this directive.', on_delete=django.db.models.deletion.PROTECT, to='talos_frontal.systemdirectiveidentifier'),
        ),
    ]
