# Generated by Django 6.0 on 2026-01-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_frontal', '0006_systemdirectiveidentifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consciousstream',
            name='model_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consciousstream',
            name='tokens_input',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consciousstream',
            name='tokens_output',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consciousstream',
            name='used_prompt',
            field=models.TextField(blank=True, help_text='The exact prompt sent to the model.'),
        ),
        migrations.AddField(
            model_name='systemdirective',
            name='context_window_size',
            field=models.IntegerField(default=32768, help_text='Max context window (e.g. 4096, 8192, 128k)'),
        ),
        migrations.AddField(
            model_name='systemdirective',
            name='max_output_tokens',
            field=models.IntegerField(default=1024, help_text='Limit response length'),
        ),
        migrations.AddField(
            model_name='systemdirective',
            name='temperature',
            field=models.FloatField(default=0.1, help_text='Creativity (0.0 - 1.0)'),
        ),
    ]
