# Generated by Django 6.0 on 2026-01-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_frontal', '0007_consciousstream_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consciousstream',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='consciousstream',
            name='used_prompt',
            field=models.TextField(blank=True, default='', help_text='The exact prompt sent to the model.'),
        ),
    ]
