# Generated by Django 6.0 on 2026-01-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_frontal', '0008_alter_consciousstream_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdirective',
            name='context_window_size',
            field=models.IntegerField(default=128000, help_text='Max context window (e.g. 4096, 8192, 128k)'),
        ),
    ]
