# Generated by Django 6.0.2 on 2026-03-09 21:25

import datetime
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('hippocampus', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PFCCommentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFCItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='PFCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PFCEpic',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('priority', models.IntegerField(default=3, help_text='1=Critical, 2=High, 3=Normal, 4=Low')),
                ('perspective', models.TextField(blank=True, default='')),
                ('assertions', models.TextField(blank=True, default='', help_text="Testable steps starting with 'Assert'")),
                ('outside', models.TextField(blank=True, default='', help_text='What NOT to do')),
                ('dod_exceptions', models.TextField(blank=True, default='')),
                ('dependencies', models.TextField(blank=True, default='')),
                ('demo_specifics', models.TextField(blank=True, default='')),
                ('complexity', models.IntegerField(default=0, help_text='Read Only - Calculated Value')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics', to='environments.projectenvironment')),
                ('owning_disc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_owned', to='identity.identitydisc')),
                ('previous_owners', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_previously_owned', to='identity.identitydisc')),
                ('source_engrams', models.ManyToManyField(blank=True, to='hippocampus.talosengram')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfcitemstatus')),
                ('tags', models.ManyToManyField(blank=True, to='prefrontal_cortex.pfctag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFCStory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('priority', models.IntegerField(default=3, help_text='1=Critical, 2=High, 3=Normal, 4=Low')),
                ('perspective', models.TextField(blank=True, default='')),
                ('assertions', models.TextField(blank=True, default='', help_text="Testable steps starting with 'Assert'")),
                ('outside', models.TextField(blank=True, default='', help_text='What NOT to do')),
                ('dod_exceptions', models.TextField(blank=True, default='')),
                ('dependencies', models.TextField(blank=True, default='')),
                ('demo_specifics', models.TextField(blank=True, default='')),
                ('complexity', models.IntegerField(default=0, help_text='Worker Calculated.')),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='prefrontal_cortex.pfcepic')),
                ('owning_disc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_owned', to='identity.identitydisc')),
                ('previous_owners', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_previously_owned', to='identity.identitydisc')),
                ('source_engrams', models.ManyToManyField(blank=True, to='hippocampus.talosengram')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfcitemstatus')),
                ('tags', models.ManyToManyField(blank=True, to='prefrontal_cortex.pfctag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFCTask',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('owning_disc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_owned', to='identity.identitydisc')),
                ('previous_owners', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_previously_owned', to='identity.identitydisc')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfcitemstatus')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prefrontal_cortex.pfcstory')),
                ('tags', models.ManyToManyField(blank=True, to='prefrontal_cortex.pfctag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFCComment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfccommentstatus')),
                ('epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prefrontal_cortex.pfcepic')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prefrontal_cortex.pfcstory')),
                ('tags', models.ManyToManyField(blank=True, to='prefrontal_cortex.pfctag')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prefrontal_cortex.pfctask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
