# Generated by Django 6.0.2 on 2026-02-28 19:36

import datetime
import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='PFCItemStatus',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=254, unique=True
                    ),
                ),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='PFCTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=254, unique=True
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PFCEpic',
            fields=[
                (
                    'created',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'modified',
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ('delta', models.DurationField(default=datetime.timedelta)),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=254, unique=True
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'vector',
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                (
                    'environment',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='epics',
                        to='environments.projectenvironment',
                    ),
                ),
                (
                    'status',
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='prefrontal_cortex.pfcitemstatus',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        blank=True, to='prefrontal_cortex.pfctag'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFCStory',
            fields=[
                (
                    'created',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'modified',
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ('delta', models.DurationField(default=datetime.timedelta)),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=254, unique=True
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'vector',
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                (
                    'epic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stories',
                        to='prefrontal_cortex.pfcepic',
                    ),
                ),
                (
                    'status',
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='prefrontal_cortex.pfcitemstatus',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        blank=True, to='prefrontal_cortex.pfctag'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFCTask',
            fields=[
                (
                    'created',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'modified',
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ('delta', models.DurationField(default=datetime.timedelta)),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=254, unique=True
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'vector',
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                (
                    'status',
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='prefrontal_cortex.pfcitemstatus',
                    ),
                ),
                (
                    'story',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tasks',
                        to='prefrontal_cortex.pfcstory',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        blank=True, to='prefrontal_cortex.pfctag'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFCComment',
            fields=[
                (
                    'created',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    'modified',
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('text', models.TextField()),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'epic',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='prefrontal_cortex.pfcepic',
                    ),
                ),
                (
                    'story',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='prefrontal_cortex.pfcstory',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        blank=True, to='prefrontal_cortex.pfctag'
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='prefrontal_cortex.pfctask',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
