# Generated by Django 6.0.2 on 2026-03-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippocampus', '0002_rename_heads_talosengram_spikes'),
        ('prefrontal_cortex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfcepic',
            name='assertions',
            field=models.TextField(blank=True, default='', help_text="Testable steps starting with 'Assert'"),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='complexity',
            field=models.IntegerField(default=0, help_text='Read Only - Calculated Value'),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='demo_specifics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='dependencies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='dod_exceptions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='outside',
            field=models.TextField(blank=True, default='', help_text='What NOT to do'),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='perspective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='priority',
            field=models.IntegerField(default=3, help_text='1=Critical, 2=High, 3=Normal, 4=Low'),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='source_engrams',
            field=models.ManyToManyField(blank=True, to='hippocampus.talosengram'),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='assertions',
            field=models.TextField(blank=True, default='', help_text="Testable steps starting with 'Assert'"),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='complexity',
            field=models.IntegerField(default=0, help_text='Worker Calculated.'),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='demo_specifics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='dependencies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='dod_exceptions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='outside',
            field=models.TextField(blank=True, default='', help_text='What NOT to do'),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='perspective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='priority',
            field=models.IntegerField(default=3, help_text='1=Critical, 2=High, 3=Normal, 4=Low'),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='source_engrams',
            field=models.ManyToManyField(blank=True, to='hippocampus.talosengram'),
        ),
    ]
