# Generated by Django 6.0.2 on 2026-03-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefrontal_cortex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pfcitemstatus',
            options={'ordering': ['id'], 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
