# Generated by Django 6.0.3 on 2026-04-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_identity_genome_identityaddon_genome_and_more'),
        ('prefrontal_cortex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfcepic',
            name='owning_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to='identity.identitydisc'),
        ),
        migrations.AlterField(
            model_name='pfcstory',
            name='owning_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to='identity.identitydisc'),
        ),
        migrations.AlterField(
            model_name='pfctask',
            name='owning_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to='identity.identitydisc'),
        ),
    ]
