# Generated by Django 6.0.2 on 2026-03-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_identityaddon_function_slug'),
        ('prefrontal_cortex', '0002_pfcepic_assertions_pfcepic_complexity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFCCommentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='owning_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_owned', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='previous_owners',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_previously_owned', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='owning_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_owned', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='previous_owners',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_previously_owned', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='pfctask',
            name='owning_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_owned', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='pfctask',
            name='previous_owners',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_previously_owned', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='pfccomment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfccommentstatus'),
        ),
    ]
