# Generated by Django 6.0.2 on 2026-03-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefrontal_cortex', '0002_alter_pfcitemstatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfcepic',
            name='status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfcitemstatus'),
        ),
        migrations.AlterField(
            model_name='pfcstory',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfcitemstatus'),
        ),
        migrations.AlterField(
            model_name='pfctask',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfcitemstatus'),
        ),
    ]
