# Generated by Django 6.0.2 on 2026-02-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefrontal_cortex', '0002_rename_comment_pfccomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemStatus',
            new_name='PFCItemStatus',
        ),
    ]
