# Generated by Django 6.0.2 on 2026-03-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefrontal_cortex', '0003_pfccommentstatus_pfcepic_owning_disc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfcepic',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfcitemstatus'),
        ),
        migrations.AlterField(
            model_name='pfcstory',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfcitemstatus'),
        ),
        migrations.AlterField(
            model_name='pfctask',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='prefrontal_cortex.pfcitemstatus'),
        ),
    ]
