# Generated by Django 6.0.2 on 2026-02-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0006_alter_projectenvironment_description_and_more'),
        ('prefrontal_cortex', '0003_rename_itemstatus_pfcitemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfcepic',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics', to='environments.projectenvironment'),
        ),
    ]
