# Generated by Django 6.0.2 on 2026-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefrontal_cortex', '0004_pfcepic_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pfccomment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='prefrontal_cortex.pfctag'),
        ),
        migrations.AddField(
            model_name='pfcepic',
            name='tags',
            field=models.ManyToManyField(blank=True, to='prefrontal_cortex.pfctag'),
        ),
        migrations.AddField(
            model_name='pfcstory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='prefrontal_cortex.pfctag'),
        ),
        migrations.AddField(
            model_name='pfctask',
            name='tags',
            field=models.ManyToManyField(blank=True, to='prefrontal_cortex.pfctag'),
        ),
    ]
