# Generated by Django 6.0.2 on 2026-02-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefrontal_cortex', '0005_pfctag_pfccomment_tags_pfcepic_tags_pfcstory_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pfcitemstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
