# Generated by Django 6.0 on 2026-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('headless', models.BooleanField(default=False)),
                ('staging', models.BooleanField(default=False)),
                ('steam', models.BooleanField(default=False)),
            ],
        ),
    ]
