# Generated by Django 6.0 on 2026-01-07 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0003_alter_projectenvironment_agent_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraExecutable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('slug', models.SlugField(help_text='Internal ID for bridge mapping', unique=True)),
                ('path_template', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Hydra Executable',
            },
        ),
        migrations.CreateModel(
            name='HydraHeadStatus',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpawnStatus',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpellOutcome',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=254)),
                ('outcome_config', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpellOutcomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('project_environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment')),
                ('executables', models.ManyToManyField(blank=True, to='hydra.hydraexecutable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpawn',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_data', models.TextField(blank=True, help_text='Serialized JSON context variables')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraenvironment')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraspawnstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraHead',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.UUIDField(blank=True, null=True)),
                ('spell_log', models.TextField(blank=True)),
                ('execution_log', models.TextField(blank=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraheadstatus')),
                ('spawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='hydra.hydraspawn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraexecutable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraResult',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report', models.CharField(blank=True, max_length=500)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra.hydrahead')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraspell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hydrahead',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraspell'),
        ),
        migrations.CreateModel(
            name='HydraSpellbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('spells', models.ManyToManyField(blank=True, to='hydra.hydraspell')),
                ('outcomes', models.ManyToManyField(blank=True, to='hydra.hydraspelloutcomeconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hydraspawn',
            name='spellbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraspellbook'),
        ),
        migrations.CreateModel(
            name='HydraSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('flag', models.CharField(help_text="The actual flag e.g. '-clean'", max_length=100)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_switches', to='hydra.hydraexecutable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hydraspell',
            name='active_switches',
            field=models.ManyToManyField(blank=True, to='hydra.hydraswitch'),
        ),
    ]
