# Generated by Django 6.0 on 2026-01-30 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('talos_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraDistributionMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Hydra Distribution Mode',
            },
        ),
        migrations.CreateModel(
            name='HydraHeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraOutcomeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Hydra Outcome Action',
            },
        ),
        migrations.CreateModel(
            name='HydraSpawnStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpellbook',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ui_json', models.TextField(blank=True, default='{}')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraWireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpawn',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_data', models.TextField(blank=True, help_text='Serialized JSON context variables')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraspawnstatus')),
                ('spellbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydra.hydraspellbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('distribution_mode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hydra.hydradistributionmode')),
                ('switches', models.ManyToManyField(blank=True, to='environments.talosexecutableswitch')),
                ('talos_executable', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='environments.talosexecutable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpellArgumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=10)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.talosexecutableargument')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra.hydraspell')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HydraSpellbookNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_json', models.TextField(blank=True, default='{}')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra.hydraspell')),
                ('spellbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='hydra.hydraspellbook')),
            ],
        ),
        migrations.CreateModel(
            name='HydraHead',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.UUIDField(blank=True, null=True)),
                ('spell_log', models.TextField(blank=True)),
                ('execution_log', models.TextField(blank=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('provenance', models.ForeignKey(blank=True, help_text='The Head that triggered this execution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='hydra.hydrahead')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talos_agent.talosagentregistry')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraheadstatus')),
                ('spawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='hydra.hydraspawn')),
                ('spell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydra.hydraspell')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydra.hydraspellbooknode')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='HydraSpellOutcomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('source_path_template', models.CharField(default='', help_text='Source path with {placeholders}', max_length=500)),
                ('dest_path_template', models.CharField(blank=True, default='', help_text='Destination path (if Copy/Move)', max_length=500)),
                ('must_exist', models.BooleanField(default=True, help_text='Fail if source missing?')),
                ('action', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraoutcomeaction')),
                ('spell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_configs', to='hydra.hydraspell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpellTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_targets', to='hydra.hydraspell')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talos_agent.talosagentregistry')),
            ],
            options={
                'verbose_name': 'Hydra Spell Target',
                'unique_together': {('spell', 'target')},
            },
        ),
        migrations.CreateModel(
            name='HydraSpellbookConnectionWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('spellbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wires', to='hydra.hydraspellbook')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='hydra.hydraspellbooknode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='hydra.hydraspellbooknode')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hydra.hydrawiretype')),
            ],
            options={
                'verbose_name': 'Wire / Connection',
                'unique_together': {('spellbook', 'source', 'target')},
            },
        ),
    ]
