# Generated by Django 6.0 on 2026-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspellbooknode',
            name='is_root',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
