# Generated by Django 6.0 on 2026-01-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspellbook',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
