# Generated by Django 6.0 on 2026-02-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0002_hydraspellbooknode_is_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspawn',
            name='parent_head',
            field=models.ForeignKey(blank=True, help_text='The Head (Node execution) in the Parent Graph that spawned this Sub-Graph.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_spawns', to='hydra.hydrahead'),
        ),
        migrations.AddField(
            model_name='hydraspellbooknode',
            name='invoked_spellbook',
            field=models.ForeignKey(blank=True, help_text='If set, this Node acts as a container that executes this Spellbook.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoking_nodes', to='hydra.hydraspellbook'),
        ),
    ]
