# Generated by Django 6.0 on 2026-01-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0002_hydraspellbook_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydraspell',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='hydraspell',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Execution sequence (1, 2, 3...)'),
        ),
    ]
