# Generated by Django 6.0 on 2026-02-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0003_hydraspawn_parent_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydraspelloutcomeconfig',
            name='action',
        ),
        migrations.RemoveField(
            model_name='hydraspelloutcomeconfig',
            name='spell',
        ),
        migrations.DeleteModel(
            name='HydraOutcomeAction',
        ),
        migrations.DeleteModel(
            name='HydraSpellOutcomeConfig',
        ),
    ]
