# Generated by Django 6.0 on 2026-01-07 22:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0003_alter_hydraspell_options_hydraspell_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydraspellbook',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
