# Generated by Django 6.0 on 2026-01-08 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0004_alter_hydraspellbook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspelloutcomeconfig',
            name='action_type',
            field=models.CharField(choices=[('COPY', 'Copy'), ('MOVE', 'Move'), ('VALIDATE_EXISTS', 'Validate Exists'), ('DELETE', 'Delete')], default='COPY', max_length=20),
        ),
        migrations.AddField(
            model_name='hydraspelloutcomeconfig',
            name='dest_path_template',
            field=models.CharField(blank=True, default='', help_text='Destination path (if Copy/Move)', max_length=500),
        ),
        migrations.AddField(
            model_name='hydraspelloutcomeconfig',
            name='must_exist',
            field=models.BooleanField(default=True, help_text='Fail if source missing?'),
        ),
        migrations.AddField(
            model_name='hydraspelloutcomeconfig',
            name='source_path_template',
            field=models.CharField(default='', help_text='Source path with {placeholders}', max_length=500),
        ),
        migrations.AddField(
            model_name='hydraspelloutcomeconfig',
            name='spell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_configs', to='hydra.hydraspell'),
        ),
    ]
