# Generated by Django 6.0 on 2026-02-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0004_remove_hydraspelloutcomeconfig_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hydraspell',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='hydraspellbook',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='hydraspellbook',
            name='name',
            field=models.CharField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='hydraspell',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hydra.hydratag'),
        ),
        migrations.AddField(
            model_name='hydraspellbook',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hydra.hydratag'),
        ),
    ]
