# Generated by Django 6.0 on 2026-01-08 15:29

import django.db.models.deletion
from django.db import migrations, models


def populate_outcome_actions(apps, schema_editor):
    HydraOutcomeAction = apps.get_model('hydra', 'HydraOutcomeAction')
    HydraOutcomeAction.objects.create(id=1, name='Copy')
    HydraOutcomeAction.objects.create(id=2, name='Move')
    HydraOutcomeAction.objects.create(id=3, name='Validate Exists')
    HydraOutcomeAction.objects.create(id=4, name='Delete')


def reverse_populate(apps, schema_editor):
    HydraOutcomeAction = apps.get_model('hydra', 'HydraOutcomeAction')
    HydraOutcomeAction.objects.filter(id__in=[1, 2, 3, 4]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0005_hydraspelloutcomeconfig_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraOutcomeAction',
            fields=[
                ('name',
                 models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Hydra Outcome Action',
            },
        ),
        migrations.RunPython(populate_outcome_actions, reverse_populate),
        migrations.RemoveField(
            model_name='hydraspelloutcomeconfig',
            name='action_type',
        ),
        migrations.AlterField(
            model_name='hydraspelloutcome',
            name='name',
            field=models.CharField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='hydraspelloutcomeconfig',
            name='action',
            field=models.ForeignKey(default=1,
                                    null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='hydra.hydraoutcomeaction'),
        ),
    ]
