# Generated by Django 6.0 on 2026-02-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0005_hydratag_hydraspell_is_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspellbooknode',
            name='distribution_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydra.hydradistributionmode'),
        ),
    ]
