# Generated by Django 6.0 on 2026-01-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0006_hydraoutcomeaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HydraSpellOutcome',
        ),
    ]
