# Generated by Django 6.0 on 2026-02-10 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_projectenvironment_projectenvironmentcontextvariable_and_more'),
        ('hydra', '0006_hydraspellbooknode_distribution_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspawn',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment'),
        ),
        migrations.AddField(
            model_name='hydraspellbook',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment'),
        ),
        migrations.AddField(
            model_name='hydraspellbooknode',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment'),
        ),
    ]
