# Generated by Django 6.0 on 2026-01-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0007_delete_hydraspelloutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraexecutable',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
