# Generated by Django 6.0 on 2026-02-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0007_hydraspawn_environment_hydraspellbook_environment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraSpellBookNodeContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=254, unique=True)),
                ('value', models.TextField(blank=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra.hydraspellbooknode')),
            ],
        ),
        migrations.CreateModel(
            name='HydraSpellContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=254, unique=True)),
                ('value', models.TextField(blank=True)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra.hydraspell')),
            ],
        ),
    ]
