# Generated by Django 6.0 on 2026-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0008_hydraspellbooknodecontext_hydraspellcontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydraspellbooknodecontext',
            name='key',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='hydraspellcontext',
            name='key',
            field=models.CharField(max_length=254),
        ),
    ]
