# Generated by Django 6.0 on 2026-01-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0008_hydraexecutable_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydraspellbook',
            name='outcomes',
        ),
    ]
