# Generated by Django 6.0 on 2026-01-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0009_remove_hydraspellbook_outcomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraExecutableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
