# Generated by Django 6.0 on 2026-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0009_alter_hydraspellbooknodecontext_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspell',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
