# Generated by Django 6.0 on 2026-02-15 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0010_hydraspell_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrahead',
            name='delta',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='hydraspawn',
            name='delta',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
