# Generated by Django 6.0 on 2026-01-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0010_hydraexecutabletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraexecutable',
            name='type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraexecutabletype'),
        ),
    ]
