# Generated by Django 6.0 on 2026-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_talosexecutable_talosexecutableswitch_and_more'),
        ('hydra', '0011_hydraexecutable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspell',
            name='switches',
            field=models.ManyToManyField(blank=True, to='environments.talosexecutableswitch'),
        ),
    ]
