# Generated by Django 6.0 on 2026-02-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0011_hydrahead_delta_hydraspawn_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrahead',
            name='blackboard',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
