# Generated by Django 6.0 on 2026-02-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0012_hydrahead_blackboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydraspawn',
            name='context_data',
        ),
    ]
