# Generated by Django 6.0 on 2026-01-21 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_talosexecutable_talosexecutableswitch_and_more'),
        ('hydra', '0012_hydraspell_switches'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspell',
            name='talos_executable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='environments.talosexecutable'),
        ),
    ]
