# Generated by Django 6.0 on 2026-02-16 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0013_remove_hydraspawn_context_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydraspellbooknode',
            name='distribution_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydra.hydradistributionmode'),
        ),
    ]
