# Generated by Django 6.0 on 2026-01-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0007_talosexecutableargument_and_more'),
        ('hydra', '0013_hydraspell_talos_executable'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraSpellArgumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=10)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.talosexecutableargument')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra.hydraspell')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
