# Generated by Django 6.0 on 2026-01-22 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0014_hydraspellargumentassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydraspell',
            name='executable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraexecutable'),
        ),
    ]
