# Generated by Django 6.0 on 2026-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0014_alter_hydraspellbooknode_distribution_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydradistributionmode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hydraspell',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hydraspellbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
