# Generated by Django 6.0.2 on 2026-02-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0015_alter_hydradistributionmode_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydrahead',
            old_name='spell_log',
            new_name='application_log',
        ),
    ]
