# Generated by Django 6.0 on 2026-01-26 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_buildjob_target_environment_and_more'),
        ('hydra', '0015_alter_hydraspell_executable'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraDistributionMode',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Hydra Distribution Mode',
            },
        ),
        migrations.CreateModel(
            name='HydraSpellTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_targets', to='hydra.hydraspell')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.remotetarget')),
            ],
            options={
                'verbose_name': 'Hydra Spell Target',
                'unique_together': {('spell', 'target')},
            },
        ),
    ]
