# Generated by Django 6.0 on 2026-01-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0016_hydradistributionmode_hydraspelltarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydradistributionmode',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
