# Generated by Django 6.0 on 2026-01-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0017_hydradistributionmode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraspell',
            name='distribution_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hydra.hydradistributionmode'),
        ),
    ]
