# Generated by Django 6.0 on 2026-01-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_buildjob_target_environment_and_more'),
        ('hydra', '0018_hydraspell_distribution_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrahead',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.remotetarget'),
        ),
    ]
