# Generated by Django 6.0 on 2026-01-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0019_hydrahead_target'),
        ('talos_agent', '0003_talosagentregistry_talosagentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydraspawn',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='hydraexecutable',
            name='type',
        ),
        migrations.RemoveField(
            model_name='hydraspell',
            name='executable',
        ),
        migrations.RemoveField(
            model_name='hydraswitch',
            name='executable',
        ),
        migrations.RemoveField(
            model_name='hydraspell',
            name='active_switches',
        ),
        migrations.AlterField(
            model_name='hydrahead',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='talos_agent.talosagentregistry'),
        ),
        migrations.AlterField(
            model_name='hydraspelltarget',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talos_agent.talosagentregistry'),
        ),
        migrations.DeleteModel(
            name='HydraEnvironment',
        ),
        migrations.DeleteModel(
            name='HydraExecutable',
        ),
        migrations.DeleteModel(
            name='HydraSwitch',
        ),
    ]
