# Generated by Django 6.0 on 2026-01-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0020_remove_hydraspawn_environment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HydraExecutableType',
        ),
    ]
