# Generated by Django 6.0 on 2026-01-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0021_delete_hydraexecutabletype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydrahead',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='hydraspell',
            options={},
        ),
        migrations.RemoveField(
            model_name='hydraspell',
            name='order',
        ),
        migrations.RemoveField(
            model_name='hydraspellbook',
            name='spells',
        ),
        migrations.AddField(
            model_name='hydrahead',
            name='provenance',
            field=models.ForeignKey(blank=True, help_text='The Head that triggered this execution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='hydra.hydrahead'),
        ),
        migrations.AddField(
            model_name='hydraspellbook',
            name='ui_json',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='hydraspellbook',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='HydraSpellbookNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_json', models.TextField(blank=True, default='{}')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra.hydraspell')),
                ('spellbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='hydra.hydraspellbook')),
            ],
        ),
        migrations.CreateModel(
            name='HydraSpellbookConnectionWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('spellbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wires', to='hydra.hydraspellbook')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='hydra.hydraspellbooknode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='hydra.hydraspellbooknode')),
            ],
            options={
                'verbose_name': 'Wire / Connection',
                'unique_together': {('spellbook', 'source', 'target')},
            },
        ),
        migrations.AddField(
            model_name='hydrahead',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hydra.hydraspellbooknode'),
        ),
        migrations.DeleteModel(
            name='HydraResult',
        ),
    ]
