# Generated by Django 6.0 on 2026-01-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0022_alter_hydrahead_options_alter_hydraspell_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraSpellbookConnectionWireStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='hydraspellbookconnectionwire',
            name='name',
        ),
        migrations.AddField(
            model_name='hydraspellbookconnectionwire',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
