# Generated by Django 6.0 on 2026-01-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0023_hydraspellbookconnectionwirestatus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HydraSpellbookConnectionWireStatus',
        ),
        migrations.AlterField(
            model_name='hydraheadstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hydraspawnstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
