# Generated by Django 6.0 on 2026-01-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0024_delete_hydraspellbookconnectionwirestatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraWireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
