# Generated by Django 6.0 on 2026-01-29 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0026_hydraspellbookconnectionwire_type'),
        ('talos_agent', '0003_talosagentregistry_talosagentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrahead',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydra.hydraspellbooknode'),
        ),
        migrations.AlterField(
            model_name='hydrahead',
            name='spell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydra.hydraspell'),
        ),
        migrations.AlterField(
            model_name='hydrahead',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talos_agent.talosagentregistry'),
        ),
        migrations.AlterField(
            model_name='hydraspawn',
            name='spellbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydra.hydraspellbook'),
        ),
    ]
