#!/bin/sh
# ------------------------------------------------------------------
# Are-Self NGINX Entrypoint — TLS Detection & Config Generation
# ------------------------------------------------------------------
# Runs before NGINX starts. Detects whether TLS certificates exist
# and writes the appropriate nginx config.
#
# Routing:
#   API paths  → Daphne  (Django/ASGI on host:8000)
#   Everything → Vite    (React dev server on host:5173)
#
# HTTPS mode: cert.pem + key.pem present in nginx/certs/
#   - Port 443: HTTPS reverse proxy
#   - Port 80:  Redirects all traffic to HTTPS
#
# HTTP mode: no certs (default)
#   - Port 80:  Plain HTTP reverse proxy
# ------------------------------------------------------------------

CERT_FILE="/etc/nginx/certs/cert.pem"
KEY_FILE="/etc/nginx/certs/key.pem"
CONF_OUT="/etc/nginx/conf.d/default.conf"

DAPHNE_HOST="${DAPHNE_HOST:-host.docker.internal}"
DAPHNE_PORT="${DAPHNE_PORT:-8000}"

UI_HOST="${UI_HOST:-host.docker.internal}"
UI_PORT="${UI_PORT:-5173}"

DAPHNE_UPSTREAM="http://${DAPHNE_HOST}:${DAPHNE_PORT}"
UI_UPSTREAM="http://${UI_HOST}:${UI_PORT}"

# Shared proxy settings for a given upstream
proxy_to() {
    cat <<PROXY
        proxy_pass $1;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
PROXY
}

# The full set of location blocks shared by HTTP and HTTPS modes.
# API paths go to Daphne, everything else goes to Vite.
# Vite's HMR websocket needs Upgrade/Connection headers which are
# already in proxy_to().
locations() {
    cat <<LOCATIONS
    # --- Django / Daphne API paths ---

    location = /mcp {
$(proxy_to "$DAPHNE_UPSTREAM")
    }

    location = /mcp/ {
$(proxy_to "$DAPHNE_UPSTREAM")
    }

    location /api/ {
$(proxy_to "$DAPHNE_UPSTREAM")
    }

    location /api-auth/ {
$(proxy_to "$DAPHNE_UPSTREAM")
    }

    location /admin/ {
$(proxy_to "$DAPHNE_UPSTREAM")
    }

    location /static/ {
$(proxy_to "$DAPHNE_UPSTREAM")
    }

    location /central_nervous_system/ {
$(proxy_to "$DAPHNE_UPSTREAM")
    }

    # Channels websocket endpoints
    location /ws/ {
$(proxy_to "$DAPHNE_UPSTREAM")
    }

    # --- Custom landing page at exactly / ---
    # Exact match means only the bare root hits the static file; every
    # other path (including React routes like /dashboard) still falls
    # through to the Vite dev server below.
    location = / {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    # --- Everything else: Vite dev server (React) ---

    location / {
$(proxy_to "$UI_UPSTREAM")
    }
LOCATIONS
}

if [ -f "$CERT_FILE" ] && [ -f "$KEY_FILE" ]; then
    echo "[Are-Self NGINX] TLS certificates detected. HTTPS mode."
    cat > "$CONF_OUT" <<EOF
# --- Generated by Are-Self (HTTPS mode) ---

server {
    listen 80;
    server_name _;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

$(locations)
}
EOF

else
    echo "[Are-Self NGINX] No TLS certificates. HTTP mode."
    cat > "$CONF_OUT" <<EOF
# --- Generated by Are-Self (HTTP mode) ---

server {
    listen 80;
    server_name _;

$(locations)
}
EOF

fi

echo "[Are-Self NGINX] Config written to ${CONF_OUT}"
