# Generated by Django 6.0.3 on 2026-04-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('version', models.CharField(max_length=254)),
                ('author', models.CharField(max_length=254)),
                ('license', models.CharField(max_length=254)),
                ('manifest_hash', models.CharField(max_length=254)),
                ('manifest_json', models.JSONField()),
            ],
            options={
                'verbose_name': 'Neural Modifier',
                'verbose_name_plural': 'Neural Modifiers',
            },
        ),
        migrations.CreateModel(
            name='NeuralModifierInstallationEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Neural Modifier Installation Event Type',
                'verbose_name_plural': 'Neural Modifier Installation Event Types',
            },
        ),
        migrations.CreateModel(
            name='NeuralModifierStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Neural Modifier Status',
                'verbose_name_plural': 'Neural Modifier Statuses',
            },
        ),
        migrations.CreateModel(
            name='NeuralModifierInstallationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('installation_manifest', models.JSONField()),
                ('neural_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_logs', to='neuroplasticity.neuralmodifier')),
            ],
            options={
                'verbose_name': 'Neural Modifier Installation Log',
                'verbose_name_plural': 'Neural Modifier Installation Logs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NeuralModifierInstallationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_data', models.JSONField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuroplasticity.neuralmodifierinstallationeventtype')),
                ('neural_modifier_installation_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='neuroplasticity.neuralmodifierinstallationlog')),
            ],
            options={
                'verbose_name': 'Neural Modifier Installation Event',
                'verbose_name_plural': 'Neural Modifier Installation Events',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='neuralmodifier',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuroplasticity.neuralmodifierstatus'),
        ),
        migrations.CreateModel(
            name='NeuralModifierContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('neural_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='neuroplasticity.neuralmodifier')),
            ],
            options={
                'verbose_name': 'Neural Modifier Contribution',
                'verbose_name_plural': 'Neural Modifier Contributions',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='neuroplasti_content_666299_idx')],
            },
        ),
    ]
