# Generated by Django 6.0.3 on 2026-04-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuroplasticity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='neuralmodifiercontribution',
            name='neuroplasti_content_666299_idx',
        ),
        migrations.DeleteModel(
            name='NeuralModifierContribution',
        ),
    ]
