from django.db import models

from common.constants import STANDARD_CHARFIELD_LENGTH
from common.models import (
    CreatedMixin,
    DefaultFieldsMixin,
    DescriptionMixin,
    ModifiedMixin,
)
from talos_reasoning.models import ReasoningStatusMixin, ReasoningTurn


class ToolParameterType(DefaultFieldsMixin, DescriptionMixin):
    """
    Lookup table for strict JSON types (OpenAI/Ollama spec).
    Fixtures: 1=String, 2=Number, 3=Integer, 4=Boolean, 5=Array, 6=Object, 7=Null.
    """

    class Meta:
        verbose_name = 'Parameter Type'
        verbose_name_plural = 'Parameter Types'


class ToolDefinition(DefaultFieldsMixin, DescriptionMixin):
    """
    The Registry for AI Tools.
    Defines the function signature available to the LLM.
    """

    is_async = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class ToolParameter(DefaultFieldsMixin, DescriptionMixin):
    """
    A strictly typed argument for a ToolDefinition.
    """

    type = models.ForeignKey(
        ToolParameterType, on_delete=models.PROTECT, related_name='usages'
    )

    # Maybe if we need it...
    # If this parameter is an array, what is the type of the items?
    # (Optional, for advanced schema generation)
    # item_type = models.ForeignKey(ToolParameterType, ...)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f'{self.name} ({self.type.name})'


class ToolParameterAssignment(CreatedMixin, ModifiedMixin):
    """
    The Link Table.
    Inherits strictly from timestamp mixins to avoid unique name constraints.
    """

    tool = models.ForeignKey(
        ToolDefinition, on_delete=models.CASCADE, related_name='assignments'
    )
    parameter = models.ForeignKey(
        ToolParameter, on_delete=models.CASCADE, related_name='tool_assignments'
    )
    required = models.BooleanField(default=True)

    class Meta:
        ordering = ['tool', 'parameter__name']
        unique_together = ('tool', 'parameter')

    def __str__(self):
        req = '*' if self.required else ''
        return f'{self.tool.name} -> {self.parameter.name}{req}'


class ParameterEnum(CreatedMixin, ModifiedMixin):
    """Joined table for parameters that have strict pre-defined values."""

    parameter = models.ForeignKey(
        ToolParameter, related_name='enum_values', on_delete=models.CASCADE
    )
    value = models.CharField(max_length=STANDARD_CHARFIELD_LENGTH)

    class Meta:
        ordering = ['value']
        unique_together = ('parameter', 'value')

    def __str__(self):
        return self.value


class ToolCall(CreatedMixin, ModifiedMixin, ReasoningStatusMixin):
    """
    The execution of a tool during a turn.
    """

    turn = models.ForeignKey(
        ReasoningTurn, on_delete=models.CASCADE, related_name='tool_calls'
    )
    tool = models.ForeignKey(ToolDefinition, on_delete=models.PROTECT)
    arguments = models.TextField(help_text='JSON payload of arguments.')
    result_payload = models.TextField(blank=True, default='')
    traceback = models.TextField(
        blank=True, default='', help_text='Error details if the tool crashed.'
    )
    call_id = models.CharField(
        max_length=255,
        blank=True,
        help_text='The unique ID generated by the LLM for this specific call.',
    )

    def __str__(self):
        return f'ToolCall: {self.tool.name} in Turn {self.turn.turn_number}'
