# Generated by Django 6.0 on 2026-01-05 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('LAUNCH', 'Started Process'), ('KILL', 'Stopped Process'), ('CRASH', 'Detected Crash'), ('DISCONNECT', 'Lost Connection'), ('RECONNECT', 'Restored Connection'), ('UPDATE', 'Agent Code Updated')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.remotetarget')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage_mb', models.FloatField(default=0.0)),
                ('is_functioning', models.BooleanField(default=False)),
                ('is_alive', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.remotetarget')),
            ],
            options={
                'verbose_name_plural': 'Agent Telemetry',
                'ordering': ['-timestamp'],
            },
        ),
    ]
