# Generated by Django 6.0 on 2026-01-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talos_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttelemetry',
            name='storage_info',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='agenttelemetry',
            name='storage_ok',
            field=models.BooleanField(default=False),
        ),
    ]
