# Generated by Django 6.0.2 on 2026-02-28 19:36

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('talos_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraDistributionMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Hydra Distribution Mode',
            },
        ),
        migrations.CreateModel(
            name='HydraHeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraSpawnStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HydraWireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydraHead',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.UUIDField(blank=True, null=True)),
                ('application_log', models.TextField(blank=True)),
                ('execution_log', models.TextField(blank=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('blackboard', models.JSONField(blank=True, default=dict)),
                ('provenance', models.ForeignKey(blank=True, help_text='The Head that triggered this execution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='central_nervous_system.hydrahead')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talos_agent.talosagentregistry')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central_nervous_system.hydraheadstatus')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='HydraSpawn',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment')),
                ('parent_head', models.ForeignKey(blank=True, help_text='The Head (Node execution) in the Parent Graph that spawned this Sub-Graph.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_spawns', to='central_nervous_system.hydrahead')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central_nervous_system.hydraspawnstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hydrahead',
            name='spawn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='central_nervous_system.hydraspawn'),
        ),
        migrations.CreateModel(
            name='HydraSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('distribution_mode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='central_nervous_system.hydradistributionmode')),
                ('switches', models.ManyToManyField(blank=True, to='environments.talosexecutableswitch')),
                ('talos_executable', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='environments.talosexecutable')),
                ('tags', models.ManyToManyField(blank=True, to='central_nervous_system.hydratag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hydrahead',
            name='spell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_nervous_system.hydraspell'),
        ),
        migrations.CreateModel(
            name='HydraSpellArgumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=10)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.talosexecutableargument')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_nervous_system.hydraspell')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HydraSpellbook',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('ui_json', models.TextField(blank=True, default='{}')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment')),
                ('tags', models.ManyToManyField(blank=True, to='central_nervous_system.hydratag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hydraspawn',
            name='spellbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_nervous_system.hydraspellbook'),
        ),
        migrations.CreateModel(
            name='HydraSpellbookNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(db_index=True, default=False)),
                ('ui_json', models.TextField(blank=True, default='{}')),
                ('distribution_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_nervous_system.hydradistributionmode')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment')),
                ('invoked_spellbook', models.ForeignKey(blank=True, help_text='If set, this Node acts as a container that executes this Spellbook.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoking_nodes', to='central_nervous_system.hydraspellbook')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_nervous_system.hydraspell')),
                ('spellbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='central_nervous_system.hydraspellbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hydrahead',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_nervous_system.hydraspellbooknode'),
        ),
        migrations.CreateModel(
            name='HydraSpellBookNodeContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=254)),
                ('value', models.TextField(blank=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_nervous_system.hydraspellbooknode')),
            ],
        ),
        migrations.CreateModel(
            name='HydraSpellContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=254)),
                ('value', models.TextField(blank=True)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_nervous_system.hydraspell')),
            ],
        ),
        migrations.CreateModel(
            name='HydraSpellTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_targets', to='central_nervous_system.hydraspell')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talos_agent.talosagentregistry')),
            ],
            options={
                'verbose_name': 'Hydra Spell Target',
                'unique_together': {('spell', 'target')},
            },
        ),
        migrations.CreateModel(
            name='HydraSpellbookConnectionWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('spellbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wires', to='central_nervous_system.hydraspellbook')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='central_nervous_system.hydraspellbooknode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='central_nervous_system.hydraspellbooknode')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='central_nervous_system.hydrawiretype')),
            ],
            options={
                'verbose_name': 'Wire / Connection',
                'unique_together': {('spellbook', 'source', 'target')},
            },
        ),
    ]
