# Generated by Django 6.0.2 on 2026-02-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_nervous_system', '0001_initial'),
        ('environments', '0001_initial'),
        ('frontal_lobe', '0002_initial'),
        ('hippocampus', '0001_initial'),
        ('talos_agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HydraDistributionMode',
            new_name='CNSDistributionMode',
        ),
        migrations.RenameModel(
            old_name='HydraHead',
            new_name='CNSHead',
        ),
        migrations.RenameModel(
            old_name='HydraSpawnStatus',
            new_name='CNSSpawnStatus',
        ),
        migrations.RenameModel(
            old_name='HydraSpawn',
            new_name='CNSSpawn',
        ),
        migrations.RenameModel(
            old_name='HydraHeadStatus',
            new_name='CNSHeadStatus',
        ),
        migrations.RenameModel(
            old_name='HydraSpell',
            new_name='CNSSpell',
        ),
        migrations.RenameModel(
            old_name='HydraSpellArgumentAssignment',
            new_name='CNSSpellArgumentAssignment',
        ),
        migrations.RenameModel(
            old_name='HydraSpellbook',
            new_name='CNSSpellbook',
        ),
        migrations.RenameModel(
            old_name='HydraSpellbookConnectionWire',
            new_name='CNSSpellbookConnectionWire',
        ),
        migrations.RenameModel(
            old_name='HydraSpellbookNode',
            new_name='CNSSpellbookNode',
        ),
        migrations.RenameModel(
            old_name='HydraSpellBookNodeContext',
            new_name='CNSSpellBookNodeContext',
        ),
        migrations.RenameModel(
            old_name='HydraSpellContext',
            new_name='CNSSpellContext',
        ),
        migrations.RenameModel(
            old_name='HydraSpellTarget',
            new_name='CNSSpellTarget',
        ),
        migrations.RenameModel(
            old_name='HydraTag',
            new_name='CNSTag',
        ),
        migrations.RenameModel(
            old_name='HydraWireType',
            new_name='CNSWireType',
        ),
    ]
