# Generated by Django 6.0.3 on 2026-04-17 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central_nervous_system', '0001_initial'),
        ('environments', '0001_initial'),
        ('peripheral_nervous_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effector',
            name='executable',
            field=models.ForeignKey(default=uuid.UUID('974ed732-6f2d-47f4-9482-18d17c73086e'), on_delete=django.db.models.deletion.PROTECT, to='environments.executable'),
        ),
        migrations.AddField(
            model_name='effector',
            name='switches',
            field=models.ManyToManyField(blank=True, to='environments.executableswitch'),
        ),
        migrations.AddField(
            model_name='effector',
            name='tags',
            field=models.ManyToManyField(blank=True, to='central_nervous_system.cnstag'),
        ),
        migrations.AddField(
            model_name='effectorargumentassignment',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.executableargument'),
        ),
        migrations.AddField(
            model_name='effectorargumentassignment',
            name='effector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_nervous_system.effector'),
        ),
        migrations.AddField(
            model_name='effectorcontext',
            name='effector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_nervous_system.effector'),
        ),
        migrations.AddField(
            model_name='effectortarget',
            name='effector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_targets', to='central_nervous_system.effector'),
        ),
        migrations.AddField(
            model_name='effectortarget',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peripheral_nervous_system.nerveterminalregistry'),
        ),
        migrations.AddField(
            model_name='neuralpathway',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment'),
        ),
        migrations.AddField(
            model_name='neuralpathway',
            name='tags',
            field=models.ManyToManyField(blank=True, to='central_nervous_system.cnstag'),
        ),
        migrations.AddField(
            model_name='axon',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axons', to='central_nervous_system.neuralpathway'),
        ),
        migrations.AddField(
            model_name='neuron',
            name='distribution_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_nervous_system.cnsdistributionmode'),
        ),
        migrations.AddField(
            model_name='neuron',
            name='effector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_nervous_system.effector'),
        ),
        migrations.AddField(
            model_name='neuron',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment'),
        ),
        migrations.AddField(
            model_name='neuron',
            name='invoked_pathway',
            field=models.ForeignKey(blank=True, help_text='If set, this Node acts as a container that executes this NeuralPathway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoking_nodes', to='central_nervous_system.neuralpathway'),
        ),
        migrations.AddField(
            model_name='neuron',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neurons', to='central_nervous_system.neuralpathway'),
        ),
        migrations.AddField(
            model_name='axon',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='central_nervous_system.neuron'),
        ),
        migrations.AddField(
            model_name='axon',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='central_nervous_system.neuron'),
        ),
        migrations.AddField(
            model_name='neuroncontext',
            name='neuron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_nervous_system.neuron'),
        ),
        migrations.AddField(
            model_name='spike',
            name='effector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_nervous_system.effector'),
        ),
        migrations.AddField(
            model_name='spike',
            name='neuron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_nervous_system.neuron'),
        ),
        migrations.AddField(
            model_name='spike',
            name='provenance',
            field=models.ForeignKey(blank=True, help_text='The Spike that triggered this execution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='central_nervous_system.spike'),
        ),
        migrations.AddField(
            model_name='spike',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripheral_nervous_system.nerveterminalregistry'),
        ),
        migrations.AddField(
            model_name='spike',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central_nervous_system.spikestatus'),
        ),
        migrations.AddField(
            model_name='spiketrain',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment'),
        ),
        migrations.AddField(
            model_name='spiketrain',
            name='parent_spike',
            field=models.ForeignKey(blank=True, help_text='The Spike (Node execution) in the Parent Graph that spawned this Sub-Graph.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_trains', to='central_nervous_system.spike'),
        ),
        migrations.AddField(
            model_name='spiketrain',
            name='pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central_nervous_system.neuralpathway'),
        ),
        migrations.AddField(
            model_name='spike',
            name='spike_train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spikes', to='central_nervous_system.spiketrain'),
        ),
        migrations.AddField(
            model_name='spiketrain',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central_nervous_system.spiketrainstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='effectortarget',
            unique_together={('effector', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='axon',
            unique_together={('pathway', 'source', 'target')},
        ),
    ]
