# Generated by Django 6.0.2 on 2026-02-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_nervous_system', '0002_rename_hydradistributionmode_cnsdistributionmode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cnsdistributionmode',
            options={'verbose_name': 'CNS Distribution Mode'},
        ),
        migrations.AlterModelOptions(
            name='cnsspelltarget',
            options={'verbose_name': 'CNS Spell Target'},
        ),
    ]
