# Generated by Django 6.0.3 on 2026-04-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_nervous_system', '0002_initial'),
        ('neuroplasticity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effector',
            name='genome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AddField(
            model_name='neuralpathway',
            name='genome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
    ]
