# Generated by Django 6.0.3 on 2026-04-22 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_nervous_system', '0003_effector_genome_neuralpathway_genome'),
        ('environments', '0003_executable_genome_executableargument_genome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effector',
            name='executable',
            field=models.ForeignKey(default=uuid.UUID('974ed732-6f2d-47f4-9482-18d17c73086e'), on_delete=django.db.models.deletion.CASCADE, to='environments.executable'),
        ),
        migrations.AlterField(
            model_name='neuralpathway',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.projectenvironment'),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.projectenvironment'),
        ),
        migrations.AlterField(
            model_name='spiketrain',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.projectenvironment'),
        ),
    ]
