# Generated by Django 6.0.2 on 2026-02-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_nervous_system',
         '0003_alter_cnsdistributionmode_options_and_more'),
    ]

    operations = [
        migrations.RenameModel('CNSWireType', 'AxonType'),
        migrations.RenameModel('CNSSpellBookNodeContext', 'NeuronContext'),
        migrations.RenameModel('CNSSpellbookConnectionWire', 'Axon'),
        migrations.RenameModel('CNSSpellbookNode', 'Neuron'),
        migrations.RenameModel('CNSSpellArgumentAssignment',
                               'EffectorArgumentAssignment'),
        migrations.RenameModel('CNSSpellContext', 'EffectorContext'),
        migrations.RenameModel('CNSSpellTarget', 'EffectorTarget'),
        migrations.RenameModel('CNSSpell', 'Effector'),
        migrations.RenameModel('CNSSpawnStatus', 'SpikeTrainStatus'),
        migrations.RenameModel('CNSHeadStatus', 'SpikeStatus'),
        migrations.RenameModel('CNSSpellbook', 'NeuralPathway'),
        migrations.RenameModel('CNSSpawn', 'SpikeTrain'),
        migrations.RenameModel('CNSHead', 'Spike'),
        migrations.RenameField('EffectorArgumentAssignment', 'effector',
                               'effector'),
        migrations.RenameField('EffectorContext', 'effector', 'effector'),
        migrations.RenameField('EffectorTarget', 'effector', 'effector'),
        migrations.RenameField('NeuronContext', 'neuron', 'neuron'),
        migrations.RenameField('Neuron', 'pathway', 'pathway'),
        migrations.RenameField('Neuron', 'effector', 'effector'),
        migrations.RenameField('Neuron', 'invoked_spellbook',
                               'invoked_pathway'),
        migrations.RenameField('Axon', 'pathway', 'pathway'),
        migrations.RenameField('SpikeTrain', 'pathway', 'pathway'),
        migrations.RenameField('SpikeTrain', 'parent_spike', 'parent_spike'),
        migrations.RenameField('Spike', 'spike_train', 'spike_train'),
        migrations.RenameField('Spike', 'neuron', 'neuron'),
        migrations.RenameField('Spike', 'effector', 'effector'),
    ]
