# Generated by Django 6.0.2 on 2026-02-28 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_nervous_system', '0004_rename_metaphor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effectortarget',
            options={'verbose_name': 'CNS Effector Target'},
        ),
        migrations.AlterField(
            model_name='axon',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axons', to='central_nervous_system.neuralpathway'),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='invoked_pathway',
            field=models.ForeignKey(blank=True, help_text='If set, this Node acts as a container that executes this NeuralPathway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoking_nodes', to='central_nervous_system.neuralpathway'),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neurons', to='central_nervous_system.neuralpathway'),
        ),
        migrations.AlterField(
            model_name='spike',
            name='provenance',
            field=models.ForeignKey(blank=True, help_text='The Spike that triggered this execution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='central_nervous_system.spike'),
        ),
        migrations.AlterField(
            model_name='spike',
            name='spike_train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spikes', to='central_nervous_system.spiketrain'),
        ),
        migrations.AlterField(
            model_name='spiketrain',
            name='parent_spike',
            field=models.ForeignKey(blank=True, help_text='The Spike (Node execution) in the Parent Graph that spawned this Sub-Graph.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_trains', to='central_nervous_system.spike'),
        ),
    ]
