# Generated by Django 6.0.3 on 2026-04-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_nervous_system', '0004_alter_effector_executable_and_more'),
        ('environments', '0004_alter_projectenvironment_default_iteration_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralpathway',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environments.projectenvironment'),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environments.projectenvironment'),
        ),
        migrations.AlterField(
            model_name='spiketrain',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environments.projectenvironment'),
        ),
    ]
