# Generated by Django 6.0.3 on 2026-04-26 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_nervous_system', '0005_alter_neuralpathway_environment_and_more'),
        ('neuroplasticity', '0004_stamp_canonical_genome'),
    ]

    operations = [
        migrations.AddField(
            model_name='axon',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AddField(
            model_name='effectorargumentassignment',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AddField(
            model_name='effectorcontext',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AddField(
            model_name='neuron',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AddField(
            model_name='neuroncontext',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AlterField(
            model_name='effector',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AlterField(
            model_name='neuralpathway',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
    ]
