# Generated by Django 6.0.2 on 2026-03-23 00:20

import datetime
import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='AIMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('slug', models.SlugField(default='llama-3-70b-instruct', unique=True)),
            ],
            options={
                'verbose_name_plural': 'AI Model Families',
            },
        ),
        migrations.CreateModel(
            name='AIModelRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('elo_score', models.FloatField()),
                ('arena_battles', models.IntegerField(default=0)),
                ('confidence_interval', models.FloatField(blank=True, null=True)),
                ('source_leaderboard', models.CharField(default='lmsys', max_length=100)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIModelSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('providers_added', models.IntegerField(default=0)),
                ('models_added', models.IntegerField(default=0)),
                ('prices_updated', models.IntegerField(default=0)),
                ('models_deactivated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('key', models.CharField(help_text='Stable identifier, e.g. "ollama", "openrouter", "openai".', max_length=50, unique=True)),
                ('base_url', models.URLField(blank=True, help_text='Base URL for this provider, e.g. https://openrouter.ai/api', max_length=255, null=True)),
                ('chat_path', models.CharField(default='/v1/chat/completions', help_text='Path segment for chat completions, appended to base_url.', max_length=255)),
                ('requires_api_key', models.BooleanField(default=True, help_text='Whether this provider requires an API key for requests.')),
                ('api_key_header', models.CharField(default='Authorization', help_text='Header name used to send the API key (e.g. Authorization).', max_length=100)),
                ('api_key_env_var', models.CharField(blank=True, help_text='Environment variable name that stores the API key (e.g. OPENROUTER_API_KEY).', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Model Providers',
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_length', models.IntegerField(db_index=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('supports_vision', models.BooleanField(db_index=True, default=False)),
                ('supports_function_calling', models.BooleanField(db_index=True, default=False)),
                ('supports_parallel_function_calling', models.BooleanField(default=False)),
                ('supports_response_schema', models.BooleanField(default=False)),
                ('supports_system_messages', models.BooleanField(default=True)),
                ('supports_prompt_caching', models.BooleanField(default=False)),
                ('supports_reasoning', models.BooleanField(default=False)),
                ('supports_audio_input', models.BooleanField(default=False)),
                ('supports_audio_output', models.BooleanField(default=False)),
                ('supports_web_search', models.BooleanField(default=False)),
                ('deprecation_date', models.DateField(blank=True, null=True)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='hypothalamus.aimodelcategory')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='hypothalamus.aimodelfamily')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('rate_limited_on', models.DateTimeField(blank=True, help_text='When the 429 Too Many Requests was hit.', null=True)),
                ('rate_limit_reset_time', models.DateTimeField(blank=True, help_text='The exact time this model is allowed back into the routing pool.', null=True)),
                ('rate_limit_reset_interval', models.DurationField(blank=True, default=datetime.timedelta(seconds=60), help_text='Base cooldown duration.', null=True)),
                ('rate_limit_counter', models.IntegerField(default=0, help_text='Tracks consecutive failures for Exponential Backoff.')),
                ('rate_limit_total_failures', models.IntegerField(default=0, help_text='Tracks total failures for this model.')),
                ('provider_unique_model_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('max_input_tokens', models.IntegerField(blank=True, null=True)),
                ('max_output_tokens', models.IntegerField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothalamus.aimodel')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('input_cost_per_token', models.DecimalField(blank=True, db_index=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_character', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_character', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_token_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_token_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_character_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_reasoning_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('cache_read_input_token_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('cache_creation_input_token_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_audio_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_vector_size', models.IntegerField(blank=True, null=True)),
                ('model_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothalamus.aimodelprovider')),
            ],
            options={
                'ordering': ['-is_current', 'model_provider__provider__key'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelProviderUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('input_cost_per_token', models.DecimalField(blank=True, db_index=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_character', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_character', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_token_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_token_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_character_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_reasoning_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('cache_read_input_token_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('cache_creation_input_token_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_audio_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_vector_size', models.IntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('query_time', models.DurationField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.IntegerField(default=0)),
                ('cache_read_input_tokens', models.IntegerField(default=0)),
                ('cache_creation_input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('reasoning_tokens', models.IntegerField(default=0)),
                ('audio_tokens', models.IntegerField(default=0)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='hypothalamus.aimodel')),
                ('ai_model_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='hypothalamus.aimodelprovider')),
            ],
            options={
                'ordering': ['-is_current', 'model_provider__provider__key'],
                'abstract': False,
            },
        ),
    ]
