# Generated by Django 6.0.3 on 2026-04-17 14:09

import datetime
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIMode',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelCapabilities',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelCategory',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelCreator',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'AI Model Creators',
            },
        ),
        migrations.CreateModel(
            name='AIModelDescriptionCache',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cached_library', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelQuantization',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelRating',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elo_score', models.FloatField()),
                ('arena_battles', models.IntegerField(default=0)),
                ('confidence_interval', models.FloatField(blank=True, null=True)),
                ('source_leaderboard', models.CharField(default='lmsys', max_length=100)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIModelRole',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelSelectionFilter',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelSyncLog',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('providers_added', models.IntegerField(default=0)),
                ('models_added', models.IntegerField(default=0)),
                ('prices_updated', models.IntegerField(default=0)),
                ('models_deactivated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelSyncReport',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_families', models.JSONField(default=list)),
                ('proposed_creators', models.JSONField(default=list)),
                ('proposed_roles', models.JSONField(default=list)),
                ('proposed_quantizations', models.JSONField(default=list)),
                ('proposed_tags', models.JSONField(default=list)),
                ('proposed_versions', models.JSONField(default=list)),
                ('unenriched_model_slugs', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelTags',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embeddings', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailoverStrategy',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Failover Strategy',
                'verbose_name_plural': 'Failover Strategies',
            },
        ),
        migrations.CreateModel(
            name='FailoverStrategyStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Failover Strategy Step',
                'verbose_name_plural': 'Failover Strategy Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FailoverType',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Failover Type',
                'verbose_name_plural': 'Failover Types',
            },
        ),
        migrations.CreateModel(
            name='LiteLLMCache',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cached_catalog', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Stable identifier, e.g. "ollama", "openrouter", "openai".', max_length=50, unique=True)),
                ('base_url', models.URLField(blank=True, help_text='Base URL for this provider, e.g. https://openrouter.ai/api', max_length=255, null=True)),
                ('chat_path', models.CharField(default='/v1/chat/completions', help_text='Path segment for chat completions, appended to base_url.', max_length=255)),
                ('requires_api_key', models.BooleanField(default=True, help_text='Whether this provider requires an API key for requests.')),
                ('api_key_header', models.CharField(default='Authorization', help_text='Header name used to send the API key (e.g. Authorization).', max_length=100)),
                ('api_key_env_var', models.CharField(blank=True, help_text='Environment variable name that stores the API key.', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Model Providers',
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter_size', models.FloatField(blank=True, db_index=True, help_text='Parameter count in billions (e.g., 70.0 for 70B, 0.5 for 500M).', null=True)),
                ('context_length', models.IntegerField(db_index=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('deprecation_date', models.DateField(blank=True, null=True)),
                ('capabilities', models.ManyToManyField(blank=True, to='hypothalamus.aimodelcapabilities')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='hypothalamus.aimodelcreator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelFamily',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='llama-3-70b-instruct', unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent family. E.g., "Qwen Coder" parent is "Qwen".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfamilies', to='hypothalamus.aimodelfamily')),
            ],
            options={
                'verbose_name_plural': 'AI Model Families',
            },
        ),
        migrations.CreateModel(
            name='AIModelDescription',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('ai_models', models.ManyToManyField(blank=True, to='hypothalamus.aimodel')),
                ('categories', models.ManyToManyField(blank=True, to='hypothalamus.aimodelcategory')),
                ('families', models.ManyToManyField(blank=True, to='hypothalamus.aimodelfamily')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='hypothalamus.aimodelfamily'),
        ),
        migrations.CreateModel(
            name='AIModelProvider',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_limited_on', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_reset_time', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_reset_interval', models.DurationField(blank=True, default=datetime.timedelta(seconds=60), null=True)),
                ('rate_limit_counter', models.IntegerField(default=0)),
                ('rate_limit_total_failures', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('provider_unique_model_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('max_input_tokens', models.IntegerField(blank=True, null=True)),
                ('max_output_tokens', models.IntegerField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothalamus.aimodel')),
                ('disabled_capabilities', models.ManyToManyField(blank=True, to='hypothalamus.aimodelcapabilities')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelPricing',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_cost_per_token', models.DecimalField(blank=True, db_index=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_character', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_character', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_token_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_token_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_character_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_reasoning_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('cache_read_input_token_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('cache_creation_input_token_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_audio_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_vector_size', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('model_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothalamus.aimodelprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelProviderUsageRecord',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_cost_per_token', models.DecimalField(blank=True, db_index=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_character', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_character', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_token_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_token_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_character_above_128k_tokens', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_cost_per_reasoning_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('cache_read_input_token_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('cache_creation_input_token_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('input_cost_per_audio_token', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('output_vector_size', models.IntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('tool_payload', models.JSONField(blank=True, default=dict)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('query_time', models.DurationField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.IntegerField(default=0)),
                ('cache_read_input_tokens', models.IntegerField(default=0)),
                ('cache_creation_input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('reasoning_tokens', models.IntegerField(default=0)),
                ('audio_tokens', models.IntegerField(default=0)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='hypothalamus.aimodel')),
                ('ai_model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='hypothalamus.aimodelprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
