# Generated by Django 6.0.2 on 2026-03-23 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hypothalamus', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelproviderusagerecord',
            name='identity_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='aimodelproviderusagerecord',
            name='model_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothalamus.aimodelprovider'),
        ),
        migrations.AddField(
            model_name='aimodelrating',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_ratings', to='hypothalamus.aimodel'),
        ),
        migrations.AddField(
            model_name='aimodelprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothalamus.llmprovider'),
        ),
        migrations.AddField(
            model_name='aimodelsynclog',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.syncstatus'),
        ),
        migrations.AddIndex(
            model_name='aimodelrating',
            index=models.Index(fields=['ai_model', 'is_current'], name='hypothalamu_ai_mode_609712_idx'),
        ),
    ]
