# Generated by Django 6.0.2 on 2026-03-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'AI Model Families',
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='hypothalamus.aimodelfamily'),
        ),
        migrations.CreateModel(
            name='AIModelRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('elo_score', models.FloatField()),
                ('arena_battles', models.IntegerField(default=0)),
                ('confidence_interval', models.FloatField(blank=True, null=True)),
                ('source_leaderboard', models.CharField(default='lmsys', max_length=100)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_ratings', to='hypothalamus.aimodel')),
            ],
            options={
                'indexes': [models.Index(fields=['ai_model', 'is_current'], name='hypothalamu_ai_mode_609712_idx')],
            },
        ),
    ]
