# Generated by Django 6.0.3 on 2026-04-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hypothalamus', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelproviderusagerecord',
            name='identity_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='quantizations',
            field=models.ManyToManyField(blank=True, related_name='ai_models', to='hypothalamus.aimodelquantization'),
        ),
        migrations.AddField(
            model_name='aimodelrating',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_ratings', to='hypothalamus.aimodel'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='ai_models', to='hypothalamus.aimodelrole'),
        ),
        migrations.AddField(
            model_name='aimodelselectionfilter',
            name='local_failover',
            field=models.ForeignKey(blank=True, help_text='Explicit local model to try when the failover strategy permits it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_filter_local', to='hypothalamus.aimodelprovider'),
        ),
        migrations.AddField(
            model_name='aimodelselectionfilter',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, to='hypothalamus.aimodelcategory'),
        ),
        migrations.AddField(
            model_name='aimodelselectionfilter',
            name='preferred_model',
            field=models.ForeignKey(blank=True, help_text='Bypass vector search and use this specific provider+model first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_filter_preferred', to='hypothalamus.aimodelprovider'),
        ),
        migrations.AddField(
            model_name='aimodelselectionfilter',
            name='preferred_roles',
            field=models.ManyToManyField(blank=True, to='hypothalamus.aimodelrole'),
        ),
        migrations.AddField(
            model_name='aimodelselectionfilter',
            name='required_capabilities',
            field=models.ManyToManyField(blank=True, help_text='Hard requirement — candidate models MUST have all of these.', to='hypothalamus.aimodelcapabilities'),
        ),
        migrations.AddField(
            model_name='aimodelsyncreport',
            name='sync_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_report', to='hypothalamus.aimodelsynclog'),
        ),
        migrations.AddField(
            model_name='aimodelselectionfilter',
            name='preferred_tags',
            field=models.ManyToManyField(blank=True, to='hypothalamus.aimodeltags'),
        ),
        migrations.AddField(
            model_name='aimodeldescription',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hypothalamus.aimodeltags'),
        ),
        migrations.AddField(
            model_name='aimodelvector',
            name='ai_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_node', to='hypothalamus.aimodel'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='hypothalamus.aimodelversion'),
        ),
        migrations.AddField(
            model_name='aimodelselectionfilter',
            name='failover_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.failoverstrategy'),
        ),
        migrations.AddField(
            model_name='failoverstrategystep',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hypothalamus.failoverstrategy'),
        ),
        migrations.AddField(
            model_name='failoverstrategystep',
            name='failover_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hypothalamus.failovertype'),
        ),
        migrations.AddField(
            model_name='aimodelselectionfilter',
            name='banned_providers',
            field=models.ManyToManyField(blank=True, help_text='Never route to these providers, even as a fallback.', to='hypothalamus.llmprovider'),
        ),
        migrations.AddField(
            model_name='aimodelprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypothalamus.llmprovider'),
        ),
        migrations.AddField(
            model_name='aimodelsynclog',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.syncstatus'),
        ),
        migrations.AddIndex(
            model_name='aimodelrating',
            index=models.Index(fields=['ai_model', 'is_current'], name='hypothalamu_ai_mode_609712_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='failoverstrategystep',
            unique_together={('strategy', 'order')},
        ),
    ]
