# Generated by Django 6.0.2 on 2026-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0002_aimodelfamily_aimodel_family_aimodelrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelfamily',
            name='slug',
            field=models.SlugField(default='llama-3-70b-instruct', unique=True),
        ),
    ]
