# Generated by Django 6.0.2 on 2026-03-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelproviderusagerecord',
            name='tool_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aimodelproviderusagerecord',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='hypothalamus.aimodel'),
        ),
        migrations.AlterField(
            model_name='aimodelproviderusagerecord',
            name='ai_model_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='hypothalamus.aimodelprovider'),
        ),
    ]
