# Generated by Django 6.0.2 on 2026-03-23 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0003_aimodelproviderusagerecord_tool_payload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelCapabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelDescriptionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_library', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIModelTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_audio_input',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_audio_output',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_function_calling',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_parallel_function_calling',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_prompt_caching',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_reasoning',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_response_schema',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_system_messages',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_vision',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='supports_web_search',
        ),
        migrations.AlterField(
            model_name='aimodelprovider',
            name='rate_limit_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aimodelprovider',
            name='rate_limit_reset_interval',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=60), null=True),
        ),
        migrations.AlterField(
            model_name='aimodelprovider',
            name='rate_limit_reset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aimodelprovider',
            name='rate_limit_total_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aimodelprovider',
            name='rate_limited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='api_key_env_var',
            field=models.CharField(blank=True, help_text='Environment variable name that stores the API key.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='capabilities',
            field=models.ManyToManyField(blank=True, to='hypothalamus.aimodelcapabilities'),
        ),
        migrations.CreateModel(
            name='AIModelDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('ai_models', models.ManyToManyField(blank=True, to='hypothalamus.aimodel')),
                ('categories', models.ManyToManyField(blank=True, to='hypothalamus.aimodelcategory')),
                ('families', models.ManyToManyField(blank=True, to='hypothalamus.aimodelfamily')),
                ('tags', models.ManyToManyField(blank=True, to='hypothalamus.aimodeltags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
