# Generated by Django 6.0.2 on 2026-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0003_aimodelfamily_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='base_url',
            field=models.URLField(blank=True, help_text='Base URL for this provider, e.g. https://openrouter.ai/api', max_length=255, null=True),
        ),
    ]
