# Generated by Django 6.0.2 on 2026-03-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0004_alter_llmprovider_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='requires_api_key',
            field=models.BooleanField(default=True, help_text='Whether this provider requires an API key for requests.'),
        ),
    ]
