# Generated by Django 6.0.2 on 2026-03-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0004_aimodelcapabilities_aimodeldescriptioncache_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodelproviderusagerecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='aimodelproviderusagerecord',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='aimodelproviderusagerecord',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='aimodelproviderusagerecord',
            name='model_provider',
        ),
    ]
