# Generated by Django 6.0.2 on 2026-03-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0005_alter_llmprovider_requires_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
