# Generated by Django 6.0.2 on 2026-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0005_alter_aimodelproviderusagerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelprovider',
            name='disabled_capabilities',
            field=models.ManyToManyField(blank=True, to='hypothalamus.aimodelcapabilities'),
        ),
    ]
