# Generated by Django 6.0.2 on 2026-03-20 22:27

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0006_aimodel_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelprovider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimodelprovider',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='aimodelprovider',
            name='rate_limit_counter',
            field=models.IntegerField(default=0, help_text='Tracks consecutive failures for Exponential Backoff.'),
        ),
        migrations.AddField(
            model_name='aimodelprovider',
            name='rate_limit_reset_interval',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=60), help_text='Base cooldown duration.', null=True),
        ),
        migrations.AddField(
            model_name='aimodelprovider',
            name='rate_limit_reset_time',
            field=models.DateTimeField(blank=True, help_text='The exact time this model is allowed back into the routing pool.', null=True),
        ),
        migrations.AddField(
            model_name='aimodelprovider',
            name='rate_limit_total_failures',
            field=models.IntegerField(default=0, help_text='Tracks total failures for this model.'),
        ),
        migrations.AddField(
            model_name='aimodelprovider',
            name='rate_limited_on',
            field=models.DateTimeField(blank=True, help_text='When the 429 Too Many Requests was hit.', null=True),
        ),
    ]
