# Generated by Django 6.0.2 on 2026-03-24 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0006_aimodelprovider_disabled_capabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteLLMCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cached_catalog', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='aimodeldescriptioncache',
            name='created_at',
        ),
        migrations.AddField(
            model_name='aimodeldescriptioncache',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
