# Generated by Django 6.0.2 on 2026-03-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0012_reasoningturn_response_payload'),
        ('hypothalamus', '0007_aimodelprovider_created_aimodelprovider_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelproviderusagerecord',
            name='reasoning_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='frontal_lobe.reasoningturn'),
        ),
    ]
