# Generated by Django 6.0.2 on 2026-03-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0007_litellmcache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelprovider',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
