# Generated by Django 6.0.2 on 2026-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0008_aimodelproviderusagerecord_reasoning_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelproviderusagerecord',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aimodelproviderusagerecord',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
