# Generated by Django 6.0.2 on 2026-03-25 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0008_aimodelprovider_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'AI Model Creators',
            },
        ),
        migrations.CreateModel(
            name='AIModelQuantization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='parameter_size',
            field=models.FloatField(blank=True, db_index=True, help_text='Parameter count in billions (e.g., 70.0 for 70B, 0.5 for 500M).', null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='hypothalamus.aimodelcreator'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='quantization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='hypothalamus.aimodelquantization'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='hypothalamus.aimodelrole'),
        ),
    ]
