# Generated by Django 6.0.2 on 2026-03-25 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0009_aimodelcreator_aimodelquantization_aimodelrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='hypothalamus.aimodelversion'),
        ),
    ]
