# Generated by Django 6.0.2 on 2026-03-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0009_aimodelproviderusagerecord_request_payload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodelproviderusagerecord',
            name='reasoning_turn',
        ),
    ]
