# Generated by Django 6.0.2 on 2026-03-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0010_aimodel_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='quantization',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='role',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='quantizations',
            field=models.ManyToManyField(blank=True, related_name='ai_models', to='hypothalamus.aimodelquantization'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='ai_models', to='hypothalamus.aimodelrole'),
        ),
    ]
