# Generated by Django 6.0.2 on 2026-03-26 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0011_remove_aimodel_quantization_remove_aimodel_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailoverStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Failover Strategy',
                'verbose_name_plural': 'Failover Strategies',
            },
        ),
        migrations.CreateModel(
            name='FailoverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Failover Type',
                'verbose_name_plural': 'Failover Types',
            },
        ),
        migrations.CreateModel(
            name='AIModelSelectionFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('banned_providers', models.ManyToManyField(blank=True, help_text='Never route to these providers, even as a fallback.', to='hypothalamus.llmprovider')),
                ('local_failover', models.ForeignKey(blank=True, help_text='Explicit local model to try when the failover strategy permits it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_filter_local', to='hypothalamus.aimodelprovider')),
                ('preferred_categories', models.ManyToManyField(blank=True, to='hypothalamus.aimodelcategory')),
                ('preferred_model', models.ForeignKey(blank=True, help_text='Bypass vector search and use this specific provider+model first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_filter_preferred', to='hypothalamus.aimodelprovider')),
                ('preferred_roles', models.ManyToManyField(blank=True, to='hypothalamus.aimodelrole')),
                ('preferred_tags', models.ManyToManyField(blank=True, to='hypothalamus.aimodeltags')),
                ('required_capabilities', models.ManyToManyField(blank=True, help_text='Hard requirement — candidate models MUST have all of these.', to='hypothalamus.aimodelcapabilities')),
                ('failover_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.failoverstrategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailoverStrategyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hypothalamus.failoverstrategy')),
                ('failover_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hypothalamus.failovertype')),
            ],
            options={
                'verbose_name': 'Failover Strategy Step',
                'verbose_name_plural': 'Failover Strategy Steps',
                'ordering': ['order'],
                'unique_together': {('strategy', 'order')},
            },
        ),
    ]
