# Generated by Django 6.0.2 on 2026-03-26 16:54

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0012_failoverstrategy_failovertype_aimodelselectionfilter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='vector',
        ),
        migrations.CreateModel(
            name='AIModelVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embeddings', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('ai_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_node', to='hypothalamus.aimodel')),
            ],
        ),
    ]
