# Generated by Django 6.0.2 on 2026-04-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0013_remove_aimodel_vector_aimodelvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelfamily',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hypothalamus.aimodelfamily'),
        ),
    ]
