# Generated by Django 6.0.2 on 2026-04-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0014_aimodelfamily_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelfamily',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent family. E.g., "Qwen Coder" parent is "Qwen".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfamilies', to='hypothalamus.aimodelfamily'),
        ),
    ]
