# Generated by Django 6.0.3 on 2026-04-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothalamus', '0015_alter_aimodelfamily_parent_subfamilies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelSyncReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('proposed_families', models.JSONField(default=list)),
                ('proposed_creators', models.JSONField(default=list)),
                ('proposed_roles', models.JSONField(default=list)),
                ('proposed_quantizations', models.JSONField(default=list)),
                ('proposed_tags', models.JSONField(default=list)),
                ('proposed_versions', models.JSONField(default=list)),
                ('unenriched_model_slugs', models.JSONField(default=list)),
                ('sync_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_report', to='hypothalamus.aimodelsynclog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
