# Generated by Django 6.0 on 2026-01-30 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hydra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasoningStatus',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Reasoning Statuses',
            },
        ),
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('system_prompt_context', models.TextField(help_text='The exact text injected into the LLM system prompt to explain the tool.')),
                ('is_async', models.BooleanField(default=False)),
                ('parameters_schema', models.TextField(blank=True, default=dict, help_text='JSON schema for tool parameters.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReasoningSession',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.TextField()),
                ('rolling_context_summary', models.TextField(blank=True, default='')),
                ('max_turns', models.IntegerField(default=10)),
                ('spawn_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasoning_sessions', to='hydra.hydraspawn')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReasoningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('reasoning_prompt', models.TextField(help_text='Specific instruction for this goal.')),
                ('parent_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_goals', to='frontal_lobe.reasoninggoal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='frontal_lobe.reasoningsession')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReasoningTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('turn_number', models.IntegerField()),
                ('input_context_snapshot', models.TextField(help_text='What the AI saw at the start of this turn.')),
                ('thought_process', models.TextField(help_text='The internal monologue of the AI.')),
                ('active_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='frontal_lobe.reasoninggoal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='frontal_lobe.reasoningsession')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelevantEngram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('fact', models.TextField()),
                ('memory_hash', models.CharField(db_index=True, max_length=64)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engrams', to='frontal_lobe.reasoningsession')),
                ('source_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engrams', to='frontal_lobe.reasoningturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('arguments', models.TextField(help_text='JSON payload of arguments.')),
                ('result_payload', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='', help_text='Error details if the tool crashed.')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='frontal_lobe.reasoningturn')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.tooldefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
