# Generated by Django 6.0.3 on 2026-04-14 13:21

import datetime
import frontal_lobe.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReasoningSession',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_turns', models.IntegerField(default=100)),
                ('total_xp', models.IntegerField(default=0)),
                ('current_focus', models.IntegerField(default=10)),
                ('swarm_message_queue', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReasoningStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Reasoning Statuses',
            },
            bases=(models.Model, frontal_lobe.models.ReasoningStatusID),
        ),
        migrations.CreateModel(
            name='ReasoningTurn',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.IntegerField()),
            ],
            options={
                'ordering': ['turn_number'],
            },
        ),
        migrations.CreateModel(
            name='SessionConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('summary', models.TextField()),
                ('reasoning_trace', models.TextField(help_text='A high-level summary of the thought process.')),
                ('outcome_status', models.TextField()),
                ('recommended_action', models.TextField()),
                ('next_goal_suggestion', models.TextField(blank=True, null=True)),
                ('system_persona_and_prompt_feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
