# Generated by Django 6.0.2 on 2026-03-23 00:20

import datetime
import django.db.models.deletion
import frontal_lobe.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Human-readable name, e.g. "Ollama", "OpenRouter".', max_length=254)),
                ('key', models.CharField(help_text='Stable identifier, e.g. "ollama", "openrouter", "local".', max_length=50, unique=True)),
                ('base_url', models.URLField(help_text='Base URL for this provider, e.g. https://openrouter.ai/api', max_length=255)),
                ('chat_path', models.CharField(default='/v1/chat/completions', help_text='Path segment for chat completions, appended to base_url.', max_length=255)),
                ('requires_api_key', models.BooleanField(default=False, help_text='Whether this provider requires an API key for requests.')),
                ('api_key_header', models.CharField(default='Authorization', help_text='Header name used to send the API key (e.g. Authorization).', max_length=100)),
                ('api_key_env_var', models.CharField(blank=True, help_text='Environment variable name that stores the API key.', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Model Providers',
            },
        ),
        migrations.CreateModel(
            name='ReasoningSession',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_turns', models.IntegerField(default=100)),
                ('total_xp', models.IntegerField(default=0)),
                ('current_focus', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReasoningStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Reasoning Statuses',
            },
            bases=(models.Model, frontal_lobe.models.ReasoningStatusID),
        ),
        migrations.CreateModel(
            name='ReasoningTurn',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.IntegerField()),
            ],
            options={
                'ordering': ['turn_number'],
            },
        ),
        migrations.CreateModel(
            name='SessionConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('summary', models.TextField()),
                ('reasoning_trace', models.TextField(help_text='A high-level summary of the thought process.')),
                ('outcome_status', models.TextField()),
                ('recommended_action', models.TextField()),
                ('next_goal_suggestion', models.TextField(blank=True, null=True)),
                ('system_persona_and_prompt_feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('api_variant', models.CharField(blank=True, default='ollama', max_length=50, null=True)),
                ('context_window_size', models.IntegerField(default=32768)),
                ('cost_per_1k_input', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_per_1k_output', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='frontal_lobe.modelprovider')),
            ],
            options={
                'verbose_name_plural': 'Model Registries',
            },
        ),
    ]
