# Generated by Django 6.0 on 2026-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooldefinition',
            name='system_prompt_context',
        ),
        migrations.AddField(
            model_name='reasoningsession',
            name='message_history',
            field=models.JSONField(blank=True, default=list, help_text='The exact array of message dicts sent to the Chat API.'),
        ),
        migrations.AddField(
            model_name='toolcall',
            name='call_id',
            field=models.CharField(blank=True, help_text='The unique ID generated by the LLM for this specific call.', max_length=255),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tooldefinition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tooldefinition',
            name='parameters_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema for tool parameters.'),
        ),
    ]
