# Generated by Django 6.0.2 on 2026-02-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontal_lobe', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoningsession',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasoning_session', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='reasoninggoal',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='frontal_lobe.reasoningsession'),
        ),
        migrations.AddField(
            model_name='reasoningsession',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus'),
        ),
        migrations.AddField(
            model_name='reasoninggoal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus'),
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='last_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontal_lobe.reasoningturn'),
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='frontal_lobe.reasoningsession'),
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus'),
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='turn_goals',
            field=models.ManyToManyField(blank=True, related_name='turns', to='frontal_lobe.reasoninggoal'),
        ),
        migrations.AddField(
            model_name='sessionconclusion',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion', to='frontal_lobe.reasoningsession'),
        ),
        migrations.AddField(
            model_name='sessionconclusion',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus'),
        ),
    ]
