# Generated by Django 6.0.2 on 2026-02-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reasoningsession',
            old_name='head',
            new_name='spike',
        ),
    ]
