# Generated by Django 6.0.2 on 2026-02-18 18:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0002_remove_tooldefinition_system_prompt_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('api_variant', models.CharField(default='ollama', max_length=50)),
                ('context_window_size', models.IntegerField(default=32768)),
                ('cost_per_1k_input', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_per_1k_output', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Model Registries',
            },
        ),
        migrations.RemoveField(
            model_name='reasoninggoal',
            name='parent_goal',
        ),
        migrations.RemoveField(
            model_name='reasoninggoal',
            name='reasoning_prompt',
        ),
        migrations.AddField(
            model_name='reasoninggoal',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reasoninggoal',
            name='delta',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='reasoninggoal',
            name='rendered_goal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reasoningstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SessionConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('summary', models.TextField()),
                ('reasoning_trace', models.TextField(help_text='A high-level summary of the thought process.')),
                ('outcome_status', models.CharField(max_length=50)),
                ('recommended_action', models.CharField(max_length=100)),
                ('next_goal_suggestion', models.TextField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion', to='frontal_lobe.reasoningsession')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RelevantEngram',
        ),
    ]
