# Generated by Django 6.0.3 on 2026-04-18 14:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasoningTurnDigest',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('turn', models.OneToOneField(help_text='The turn this digest summarizes; also the digest PK.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='digest', serialize=False, to='frontal_lobe.reasoningturn')),
                ('turn_number', models.IntegerField(db_index=True, help_text='Denormalized from turn.turn_number for cheap ordering.')),
                ('status_name', models.CharField(db_index=True, help_text='Denormalized ReasoningStatus.name at the time the digest was written. Read-only shadow; the turn is still the source of truth.', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', help_text='Flattened from turn.model_usage_record.ai_model_provider.ai_model.name. Used to render "qwen2.5-coder:32b" in the turn chip without traversing four FKs.', max_length=255)),
                ('tokens_in', models.IntegerField(default=0, help_text='Input tokens from the turn ModelUsageRecord.')),
                ('tokens_out', models.IntegerField(default=0, help_text='Output tokens from the turn ModelUsageRecord.')),
                ('excerpt', models.TextField(blank=True, default='', help_text='Up to ~300 chars of the assistant thought for this turn, extracted by the same logic the frontend uses (extractThoughtFromUsageRecord): plain assistant content, or the "thought" field from an mcp_respond_to_user tool call if the assistant spoke through the tool. Truncated with an ellipsis. Not searchable, not authoritative — if you need the real content, read the turn.')),
                ('tool_calls_summary', models.JSONField(blank=True, default=list, help_text="List of {id, tool_name, success, target} dicts summarizing the turn's ToolCall records. Enough to render the Parietal Lobe chips. The id is the ToolCall pk (as a string) so the frontend can look up the full row on the fetched turn by stable id instead of array index. Args and result_payload intentionally excluded — fetch the turn detail for those.")),
                ('engram_ids', models.JSONField(blank=True, default=list, help_text='UUIDs (as strings) of engrams formed or referenced during this turn. Resolved against the engram endpoint by the frontend; not a FK/M2M because digests are meant to be nukable without touching hippocampus.')),
                ('session', models.ForeignKey(help_text='Denormalized from turn.session so the incremental-load endpoint (graph_data?since_turn_number=N) can filter digests without joining through ReasoningTurn.', on_delete=django.db.models.deletion.CASCADE, related_name='turn_digests', to='frontal_lobe.reasoningsession')),
            ],
            options={
                'verbose_name': 'reasoning turn digest',
                'verbose_name_plural': 'reasoning turn digests',
                'ordering': ['session_id', 'turn_number'],
                'indexes': [models.Index(fields=['session', 'turn_number'], name='turn_digest_session_turn_idx')],
            },
        ),
    ]
