# Generated by Django 6.0.2 on 2026-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoningsession',
            name='swarm_message_queue',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
