# Generated by Django 6.0.2 on 2026-02-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0003_modelregistry_remove_reasoninggoal_parent_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolcall',
            name='status',
        ),
        migrations.RemoveField(
            model_name='toolcall',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='toolcall',
            name='turn',
        ),
        migrations.DeleteModel(
            name='ToolDefinition',
        ),
        migrations.DeleteModel(
            name='ToolCall',
        ),
    ]
