# Generated by Django 6.0.2 on 2026-03-12 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0003_chatmessagerole'),
        ('parietal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_volatile', models.BooleanField(default=False, help_text='If True, this message (like an Addon) is excluded from historical memory.')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal_lobe.chatmessagerole')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='frontal_lobe.reasoningsession')),
                ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parietal_lobe.toolcall')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='frontal_lobe.reasoningturn')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-created'],
            },
        ),
    ]
