# Generated by Django 6.0.2 on 2026-03-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0003_rename_head_reasoningsession_spike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reasoningsession',
            old_name='identity',
            new_name='identity_disc',
        ),
    ]
