# Generated by Django 6.0.2 on 2026-04-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0004_remove_modelprovider_modelregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoningsession',
            name='current_focus',
            field=models.IntegerField(default=10),
        ),
    ]
