# Generated by Django 6.0.2 on 2026-03-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0004_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasoningturn',
            name='turn_goals',
        ),
        migrations.DeleteModel(
            name='ReasoningGoal',
        ),
    ]
