# Generated by Django 6.0.2 on 2026-03-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0004_rename_identity_reasoningsession_identity_disc'),
        ('temporal_lobe', '0005_iterationshiftparticipantstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoningsession',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasoning_session', to='temporal_lobe.iterationshiftparticipant'),
        ),
    ]
