# Generated by Django 6.0.2 on 2026-04-07 12:58
#
# Replayed from the pre-merge line; 0001_initial already has this field, but
# the node is required so 0006_layer2_turn_kind_interrupt can depend on 0005.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0004_remove_modelprovider_modelregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoningsession',
            name='current_focus',
            field=models.IntegerField(default=10),
        ),
    ]
