# Generated by Django 6.0.2 on 2026-02-19 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0015_alter_hydradistributionmode_description_and_more'),
        ('frontal_lobe', '0005_remove_reasoninggoal_delta_reasoningsession_delta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasoningsession',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='reasoningsession',
            name='message_history',
        ),
        migrations.RemoveField(
            model_name='reasoningsession',
            name='rolling_context_summary',
        ),
        migrations.AddField(
            model_name='reasoningsession',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasoning_session', to='hydra.hydraspellbooknode'),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='max_turns',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='reasoningsession',
            name='spawn_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasoning_session', to='hydra.hydraspawn'),
        ),
        migrations.AlterField(
            model_name='sessionconclusion',
            name='outcome_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sessionconclusion',
            name='recommended_action',
            field=models.TextField(),
        ),
    ]
