# Generated by Django 6.0.2 on 2026-03-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0005_remove_reasoningturn_turn_goals_delete_reasoninggoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasoningturn',
            options={'ordering': ['turn_number']},
        ),
    ]
