# Generated by Django 6.0.4 on 2026-04-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0006_layer2_turn_kind_interrupt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoningturn',
            name='turn_kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningturnkind'),
        ),
        migrations.AlterField(
            model_name='reasoningturnkind',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
