# Generated by Django 6.0.2 on 2026-03-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0007_modelprovider_and_registry_provider_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprovider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='modelprovider',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='modelprovider',
            name='name',
            field=models.CharField(db_index=True, max_length=254, unique=True),
        ),
    ]
