# Generated by Django 6.0.2 on 2026-02-19 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0007_remove_reasoningsession_node_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasoningturn',
            name='active_goal',
        ),
        migrations.RemoveField(
            model_name='reasoningturn',
            name='input_context_snapshot',
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='inference_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='tokens_input',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='tokens_output',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='turn_goals',
            field=models.ManyToManyField(blank=True, related_name='turns', to='frontal_lobe.reasoninggoal'),
        ),
    ]
