# Generated by Django 6.0.2 on 2026-03-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0008_alter_modelprovider_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprovider',
            name='name',
            field=models.CharField(help_text='Human-readable name, e.g. "Ollama", "OpenRouter".', max_length=254),
        ),
    ]
