# Generated by Django 6.0.2 on 2026-03-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0009_alter_modelprovider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelregistry',
            name='api_variant',
            field=models.CharField(blank=True, default='ollama', max_length=50, null=True),
        ),
    ]
