# Generated by Django 6.0.2 on 2026-03-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0010_alter_modelregistry_api_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessagerole',
            options={'ordering': ['id'], 'verbose_name_plural': 'Chat Message Roles'},
        ),
    ]
