# Generated by Django 6.0.2 on 2026-03-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0011_alter_chatmessagerole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoningturn',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
