# Generated by Django 6.0.2 on 2026-02-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0011_reasoningturn_last_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionconclusion',
            name='name',
        ),
        migrations.AddField(
            model_name='sessionconclusion',
            name='system_persona_and_prompt_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
