# Generated by Django 6.0.2 on 2026-03-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0012_reasoningturn_response_payload'),
        ('hypothalamus', '0010_remove_aimodelproviderusagerecord_reasoning_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasoningturn',
            name='inference_time',
        ),
        migrations.RemoveField(
            model_name='reasoningturn',
            name='request_payload',
        ),
        migrations.RemoveField(
            model_name='reasoningturn',
            name='response_payload',
        ),
        migrations.RemoveField(
            model_name='reasoningturn',
            name='thought_process',
        ),
        migrations.RemoveField(
            model_name='reasoningturn',
            name='tokens_input',
        ),
        migrations.RemoveField(
            model_name='reasoningturn',
            name='tokens_output',
        ),
        migrations.AddField(
            model_name='reasoningturn',
            name='model_usage_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypothalamus.aimodelproviderusagerecord'),
        ),
    ]
