# Generated by Django 6.0.2 on 2026-02-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal_lobe', '0012_remove_sessionconclusion_name_and_more'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoningsession',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasoning_session', to='identity.identitydisc'),
        ),
    ]
