"""Save As bug-fix coverage + the edit-metadata / preview endpoints.

Bugs spotted by inspecting a real save-as'd zip (``log-dude.zip``):

1. The new genome carried the source's manifest description verbatim
   instead of an auto-generated one.
2. The new genome's ``code/`` was a copy of the source's ``code/``,
   leaving the source's package directory orphaned inside a zip whose
   ``entry_modules`` was empty. Two installed genomes shipping the
   same package name also risked a ``sys.path`` collision.
3. ``__pycache__`` directories and ``.pyc`` files were being packed
   into both save-as zips and save zips because the rglob walk had
   no filter.

Plus tests for the two new endpoints:

4. ``POST /api/v2/neural-modifiers/<slug>/edit-metadata/`` updates the
   row's ``name`` and ``manifest_json['description']`` and re-bakes
   the catalog zip via :func:`save_graft_to_genome`. Refused on
   canonical and incubator.
5. ``GET /api/v2/neural-modifiers/<slug>/preview/`` returns a
   read-only snapshot — manifest, owned-row counts per model, code
   tree, media tree.
"""

from __future__ import annotations

import datetime
import json
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path
from unittest.mock import patch

from django.test import TestCase, override_settings
from rest_framework.test import APIClient

from identity.models import IdentityAddon
from neuroplasticity import loader
from neuroplasticity.models import (
    NeuralModifier,
    NeuralModifierStatus,
)


class _SaveAsHarness(TestCase):
    """Tmp-rooted setup that installs a source genome + media file.

    Mirrors the existing ``SaveAsRoundTripTest`` setUp but lives here
    so the new test classes don't pull on test_incubator_genome's
    setup pile.
    """

    fixtures = ['neuroplasticity/fixtures/genetic_immutables.json']

    def setUp(self):
        super().setUp()
        self._tmp_root = Path(tempfile.mkdtemp(prefix='saveas-bugfix-'))
        self.genomes_root = self._tmp_root / 'genomes'
        self.grafts_root = self._tmp_root / 'grafts'
        self.operating_room_root = self._tmp_root / 'operating_room'
        for d in (
            self.genomes_root, self.grafts_root, self.operating_room_root,
        ):
            d.mkdir()
        self._sys_path_snapshot = list(sys.path)
        self._sys_modules_snapshot = set(sys.modules.keys())
        self._settings_override = override_settings(
            NEURAL_MODIFIER_GENOMES_ROOT=str(self.genomes_root),
            NEURAL_MODIFIER_GRAFTS_ROOT=str(self.grafts_root),
            NEURAL_MODIFIER_OPERATING_ROOM_ROOT=str(self.operating_room_root),
        )
        self._settings_override.enable()

        from neuroplasticity.tests.test_modifier_lifecycle import (
            build_fake_bundle_archive,
        )
        self.source_archive = build_fake_bundle_archive(
            self.genomes_root, 'sourcer',
        )
        loader.install_genome_to_graft(self.source_archive)
        source_media = self.grafts_root / 'sourcer' / 'media'
        source_media.mkdir(parents=True, exist_ok=True)
        (source_media / 'avatar.png').write_bytes(b'PIXELS')

    def tearDown(self):
        self._settings_override.disable()
        sys.path[:] = self._sys_path_snapshot
        for name in list(sys.modules.keys()):
            if name not in self._sys_modules_snapshot:
                sys.modules.pop(name, None)
        shutil.rmtree(self._tmp_root, ignore_errors=True)
        super().tearDown()

    def _zip_names(self, archive: Path) -> set[str]:
        with zipfile.ZipFile(archive) as zf:
            return set(zf.namelist())

    def _zip_manifest(self, archive: Path, slug: str) -> dict:
        with zipfile.ZipFile(archive) as zf:
            return json.loads(
                zf.read('{0}/manifest.json'.format(slug)).decode('utf-8')
            )


class SaveAsDescriptionAutoGeneratedTest(_SaveAsHarness):
    """Fix #1 — Save As must never carry the source's description."""

    def test_source_description_does_not_leak_into_new_manifest(self):
        """Assert new genome's description ignores the source's text."""
        # Source manifest carries 'Test bundle.' (build_fake_bundle default).
        source = NeuralModifier.objects.get(slug='sourcer')
        self.assertEqual(
            source.manifest_json.get('description'), 'Test bundle.',
        )

        new_modifier = loader.save_as_genome('sourcer', 'forge_target')

        self.assertNotEqual(
            new_modifier.manifest_json.get('description'), 'Test bundle.',
        )

    def test_new_description_is_auto_generated(self):
        """Assert the new genome's description matches the forge format."""
        new_modifier = loader.save_as_genome('sourcer', 'forge_target_2')

        today = datetime.date.today().isoformat()
        expected = "Forged from 'sourcer' on {0}.".format(today)
        self.assertEqual(
            new_modifier.manifest_json.get('description'), expected,
        )


class SaveAsEmptyCodeScaffoldingTest(_SaveAsHarness):
    """Fix #2 — Save As ships an empty package, not a copy of source code."""

    def test_source_code_does_not_leak_into_new_zip(self):
        """Assert the source's package is NOT inside the new zip."""
        loader.save_as_genome('sourcer', 'forge_target_3')

        zip_path = self.genomes_root / 'forge_target_3.zip'
        names = self._zip_names(zip_path)

        for name in names:
            self.assertNotIn('are_self_fake_catalog', name)

    def test_new_zip_has_empty_package_matching_slug(self):
        """Assert the new zip ships ``code/<new_pkg>/__init__.py`` only."""
        loader.save_as_genome('sourcer', 'forge_target_4')

        zip_path = self.genomes_root / 'forge_target_4.zip'
        names = self._zip_names(zip_path)

        # New package name = slug with hyphens to underscores + _genome.
        self.assertIn(
            'forge_target_4/code/forge_target_4_genome/__init__.py', names,
        )

    def test_hyphenated_slug_uses_underscored_package_name(self):
        """Assert ``log-dude`` -> ``log_dude_genome``."""
        loader.save_as_genome('sourcer', 'log-dude')

        zip_path = self.genomes_root / 'log-dude.zip'
        names = self._zip_names(zip_path)
        self.assertIn(
            'log-dude/code/log_dude_genome/__init__.py', names,
        )

        manifest = self._zip_manifest(zip_path, 'log-dude')
        self.assertEqual(manifest['entry_modules'], ['log_dude_genome'])

    def test_new_manifest_entry_modules_match_new_package(self):
        """Assert manifest.entry_modules names the new package."""
        loader.save_as_genome('sourcer', 'forge_target_5')

        zip_path = self.genomes_root / 'forge_target_5.zip'
        manifest = self._zip_manifest(zip_path, 'forge_target_5')
        self.assertEqual(
            manifest['entry_modules'], ['forge_target_5_genome'],
        )

    def test_new_genome_actually_installs(self):
        """Assert the resulting genome installs (entry_modules resolves)."""
        new_modifier = loader.save_as_genome('sourcer', 'forge_target_6')

        # save_as_genome returns the freshly-installed modifier.
        self.assertEqual(new_modifier.status_id, NeuralModifierStatus.INSTALLED)
        graft = self.grafts_root / 'forge_target_6'
        self.assertTrue(
            (graft / 'code' / 'forge_target_6_genome' / '__init__.py').is_file(),
        )


class SaveAsPycacheFilterTest(_SaveAsHarness):
    """Fix #3 — Save As must not pack ``__pycache__`` / ``.pyc`` files."""

    def test_pyc_in_source_media_does_not_leak_into_new_zip(self):
        """Assert .pyc inside source media is filtered from the new zip."""
        # Drop a .pyc and a __pycache__ dir into the source's media tree.
        media = self.grafts_root / 'sourcer' / 'media'
        (media / 'stray.pyc').write_bytes(b'\x00\x00\x00\x00')
        cache = media / '__pycache__'
        cache.mkdir()
        (cache / 'leftover.cpython-314.pyc').write_bytes(b'\x00')

        loader.save_as_genome('sourcer', 'forge_target_7')

        zip_path = self.genomes_root / 'forge_target_7.zip'
        names = self._zip_names(zip_path)

        for name in names:
            self.assertFalse(
                name.endswith('.pyc'),
                'Unexpected .pyc in zip: {0}'.format(name),
            )
            self.assertNotIn(
                '__pycache__', name,
                'Unexpected __pycache__ in zip: {0}'.format(name),
            )


class SaveGraftPycacheFilterTest(_SaveAsHarness):
    """Fix #3 — :func:`save_graft_to_genome` must filter the same paths."""

    def test_pyc_in_source_code_does_not_leak_into_saved_zip(self):
        """Assert .pyc / __pycache__ in graft code/ are filtered on save."""
        code = self.grafts_root / 'sourcer' / 'code' / 'are_self_fake_catalog'
        cache = code / '__pycache__'
        # Python's import machinery may have already populated this dir
        # when the source genome's package was imported during install.
        cache.mkdir(exist_ok=True)
        (cache / 'leftover.cpython-314.pyc').write_bytes(b'\x00')
        (code / 'stray.pyo').write_bytes(b'\x00')

        loader.save_graft_to_genome('sourcer')

        zip_path = self.genomes_root / 'sourcer.zip'
        names = self._zip_names(zip_path)
        for name in names:
            self.assertFalse(name.endswith('.pyc'))
            self.assertFalse(name.endswith('.pyo'))
            self.assertNotIn('__pycache__', name)


class EditMetadataLoaderTest(_SaveAsHarness):
    """Fix #4 — :func:`edit_genome_metadata` updates row + re-bakes zip."""

    def test_updates_name_and_description_and_rebakes(self):
        """Assert name + description land on the row + on-disk manifest."""
        result = loader.edit_genome_metadata(
            'sourcer', name='Renamed', description='Brand new pitch.',
        )

        modifier = NeuralModifier.objects.get(slug='sourcer')
        self.assertEqual(modifier.name, 'Renamed')
        self.assertEqual(
            modifier.manifest_json['description'], 'Brand new pitch.',
        )
        self.assertEqual(modifier.manifest_json['name'], 'Renamed')
        # save_graft_to_genome bumped patch — result reports the new version.
        self.assertNotEqual(result['previous_version'], result['new_version'])

        # Zip on disk reflects the edit.
        with zipfile.ZipFile(self.genomes_root / 'sourcer.zip') as zf:
            manifest = json.loads(
                zf.read('sourcer/manifest.json').decode('utf-8'),
            )
        self.assertEqual(manifest['name'], 'Renamed')
        self.assertEqual(manifest['description'], 'Brand new pitch.')

    def test_description_only_keeps_existing_name(self):
        """Assert omitting name leaves the row's name untouched."""
        before_name = NeuralModifier.objects.get(slug='sourcer').name
        loader.edit_genome_metadata('sourcer', description='Only desc.')

        modifier = NeuralModifier.objects.get(slug='sourcer')
        self.assertEqual(modifier.name, before_name)
        self.assertEqual(modifier.manifest_json['description'], 'Only desc.')

    def test_refuses_canonical(self):
        with self.assertRaisesRegex(ValueError, 'canonical'):
            loader.edit_genome_metadata(
                NeuralModifier.CANONICAL_SLUG, description='nope',
            )

    def test_refuses_incubator(self):
        with self.assertRaisesRegex(ValueError, 'incubator'):
            loader.edit_genome_metadata(
                NeuralModifier.INCUBATOR_SLUG, description='nope',
            )

    def test_refuses_blank_name(self):
        with self.assertRaisesRegex(ValueError, 'name'):
            loader.edit_genome_metadata('sourcer', name='   ')

    def test_refuses_when_neither_field_provided(self):
        with self.assertRaisesRegex(ValueError, 'name or description'):
            loader.edit_genome_metadata('sourcer')


class EditMetadataApiTest(_SaveAsHarness):
    """End-to-end ``POST /api/v2/neural-modifiers/<slug>/edit-metadata/``."""

    def test_api_edit_metadata_200_and_persists(self):
        client = APIClient()
        res = client.post(
            '/api/v2/neural-modifiers/sourcer/edit-metadata/',
            {'name': 'API Renamed', 'description': 'API description.'},
            format='json',
        )

        self.assertEqual(res.status_code, 200, res.data)
        modifier = NeuralModifier.objects.get(slug='sourcer')
        self.assertEqual(modifier.name, 'API Renamed')
        self.assertEqual(
            modifier.manifest_json['description'], 'API description.',
        )

    def test_api_edit_metadata_400_when_neither_field(self):
        client = APIClient()
        res = client.post(
            '/api/v2/neural-modifiers/sourcer/edit-metadata/',
            {},
            format='json',
        )
        self.assertEqual(res.status_code, 400, res.data)

    def test_api_edit_metadata_400_on_incubator(self):
        client = APIClient()
        res = client.post(
            '/api/v2/neural-modifiers/incubator/edit-metadata/',
            {'description': 'nope'},
            format='json',
        )
        self.assertEqual(res.status_code, 400, res.data)


class GenomePreviewLoaderTest(_SaveAsHarness):
    """Fix #5 — :func:`genome_preview` returns the live read-only snapshot."""

    def test_preview_includes_manifest_and_row_counts(self):
        """Assert manifest + per-model row counts are populated."""
        preview = loader.genome_preview('sourcer')

        self.assertEqual(preview['slug'], 'sourcer')
        self.assertEqual(
            preview['manifest']['slug'], 'sourcer',
        )
        # build_fake_bundle ships 3 IdentityAddon rows.
        self.assertEqual(
            preview['rows_by_model']['identity.identityaddon'], 3,
        )

    def test_preview_includes_code_and_media_trees(self):
        """Assert code_tree + media_tree reflect graft layout."""
        preview = loader.genome_preview('sourcer')

        self.assertIn(
            'are_self_fake_catalog/__init__.py', preview['code_tree'],
        )
        self.assertIn('avatar.png', preview['media_tree'])

    def test_preview_filters_pycache_from_trees(self):
        """Assert __pycache__ / .pyc are filtered from code_tree + media_tree."""
        code = self.grafts_root / 'sourcer' / 'code' / 'are_self_fake_catalog'
        cache = code / '__pycache__'
        cache.mkdir(exist_ok=True)
        (cache / 'leftover.cpython-314.pyc').write_bytes(b'\x00')
        media = self.grafts_root / 'sourcer' / 'media'
        (media / 'stray.pyc').write_bytes(b'\x00')

        preview = loader.genome_preview('sourcer')

        for entry in preview['code_tree']:
            self.assertNotIn('__pycache__', entry)
            self.assertFalse(entry.endswith('.pyc'))
        for entry in preview['media_tree']:
            self.assertFalse(entry.endswith('.pyc'))

    def test_preview_refuses_canonical(self):
        with self.assertRaisesRegex(ValueError, 'canonical'):
            loader.genome_preview(NeuralModifier.CANONICAL_SLUG)

    def test_preview_allows_incubator(self):
        """Assert INCUBATOR is in scope (real grafted genome)."""
        # Build a synthetic incubator graft so the preview has something
        # to read from. This mirrors what graft_incubator does at boot.
        incubator_graft = self.grafts_root / 'incubator'
        (incubator_graft / 'code' / 'incubator_genome').mkdir(parents=True)
        (
            incubator_graft / 'code' / 'incubator_genome' / '__init__.py'
        ).write_text('')
        (incubator_graft / 'media').mkdir()
        (incubator_graft / 'manifest.json').write_text(
            json.dumps({'slug': 'incubator', 'name': 'Incubator'}) + '\n',
        )
        incubator = NeuralModifier.objects.get(pk=NeuralModifier.INCUBATOR)
        incubator.status_id = NeuralModifierStatus.INSTALLED
        incubator.manifest_json = {
            'slug': 'incubator', 'name': 'Incubator',
        }
        incubator.save()

        preview = loader.genome_preview('incubator')
        self.assertEqual(preview['slug'], 'incubator')


class GenomePreviewApiTest(_SaveAsHarness):
    """End-to-end ``GET /api/v2/neural-modifiers/<slug>/preview/``."""

    def test_api_preview_200_with_full_payload(self):
        client = APIClient()
        res = client.get('/api/v2/neural-modifiers/sourcer/preview/')

        self.assertEqual(res.status_code, 200, res.data)
        payload = res.json()
        self.assertEqual(payload['slug'], 'sourcer')
        self.assertIn('manifest', payload)
        self.assertIn('rows_by_model', payload)
        self.assertIn('code_tree', payload)
        self.assertIn('media_tree', payload)

    def test_api_preview_404_on_canonical(self):
        """Assert canonical is hidden by the viewset's queryset (404)."""
        client = APIClient()
        res = client.get(
            '/api/v2/neural-modifiers/{0}/preview/'.format(
                NeuralModifier.CANONICAL_SLUG,
            ),
        )
        self.assertEqual(res.status_code, 404)

    def test_api_preview_404_on_unknown_slug(self):
        client = APIClient()
        res = client.get('/api/v2/neural-modifiers/never-exists/preview/')
        self.assertEqual(res.status_code, 404)
