# Generated by Django 6.0.3 on 2026-04-14 13:21

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IterationDefinition',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IterationShiftParticipantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Iteration Shift Participant Status',
                'verbose_name_plural': 'Iteration Shift Participant Statuses',
            },
        ),
        migrations.CreateModel(
            name='IterationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('default_turn_limit', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('turns_consumed_in_shift', models.IntegerField(default=0)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environments.projectenvironment')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationdefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IterationShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('shift_iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iteration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='iteration',
            name='current_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='temporal_lobe.iterationshift'),
        ),
        migrations.CreateModel(
            name='IterationShiftDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('turn_limit', models.IntegerField(default=1)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationdefinition')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.shift')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('definition', 'order')},
            },
        ),
        migrations.AddField(
            model_name='iterationshift',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationshiftdefinition'),
        ),
        migrations.CreateModel(
            name='IterationShiftDefinitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_disc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.identitydisc')),
                ('shift_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationshiftdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='IterationShiftParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.identitydisc')),
                ('iteration_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationshift')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationshiftparticipantstatus')),
            ],
        ),
        migrations.AddField(
            model_name='iteration',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationstatus'),
        ),
        migrations.AddField(
            model_name='iterationshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.shift'),
        ),
        migrations.CreateModel(
            name='ShiftDefaultParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.identity')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.shift')),
            ],
        ),
    ]
