# Generated by Django 6.0.2 on 2026-03-01 20:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IterationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IterationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('turn_limit', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IterationShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationdefinition')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.shift')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('definition', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('delta', models.DurationField(default=datetime.timedelta)),
                ('name', models.CharField(max_length=254)),
                ('turns_consumed_in_shift', models.IntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='temporal_lobe.iterationdefinition')),
                ('current_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='temporal_lobe.iterationshift')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.identity')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.shift')),
            ],
        ),
    ]
