# Generated by Django 6.0.2 on 2026-03-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temporal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iterationshift',
            old_name='phase',
            new_name='shift',
        ),
    ]
