# Generated by Django 6.0.2 on 2026-03-11 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('temporal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iterationshiftdefinitionparticipant',
            name='participant',
        ),
        migrations.AddField(
            model_name='iterationshiftdefinitionparticipant',
            name='identity_disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.identitydisc'),
        ),
    ]
