# Generated by Django 6.0.2 on 2026-03-01 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_projectenvironment_default_iteration_definition'),
        ('temporal_lobe', '0002_rename_phase_iterationshift_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='environments.projectenvironment'),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
