# Generated by Django 6.0.2 on 2026-03-03 18:24

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_identityaddon_function_slug'),
        ('temporal_lobe', '0003_iteration_environment_alter_iteration_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftParticipant',
            new_name='ShiftDefaultParticipant',
        ),
        migrations.AlterModelOptions(
            name='iterationshift',
            options={},
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='turn_limit',
            new_name='default_turn_limit',
        ),
        migrations.AlterUniqueTogether(
            name='iterationshift',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='iterationshift',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iterationshift',
            name='delta',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='iterationshift',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='iterationshift',
            name='shift_iteration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iteration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iteration',
            name='current_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='temporal_lobe.iterationshift'),
        ),
        migrations.CreateModel(
            name='IterationShiftDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('turn_limit', models.IntegerField(default=1)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationdefinition')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.shift')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('definition', 'order')},
            },
        ),
        migrations.AlterField(
            model_name='iterationshift',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationshiftdefinition'),
        ),
        migrations.CreateModel(
            name='IterationShiftDefinitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.identity')),
                ('shift_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationshiftdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='IterationShiftParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.identitydisc')),
                ('iteration_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationshift')),
            ],
        ),
        migrations.RemoveField(
            model_name='iterationshift',
            name='order',
        ),
    ]
