# Generated by Django 6.0.2 on 2026-03-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporal_lobe', '0004_rename_shiftparticipant_shiftdefaultparticipant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IterationShiftParticipantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Iteration Shift Participant Status',
                'verbose_name_plural': 'Iteration Shift Participant Statuses',
            },
        ),
        migrations.AddField(
            model_name='iterationshiftparticipant',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationshiftparticipantstatus'),
        ),
    ]
