# Generated by Django 6.0.2 on 2026-03-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_projectenvironment_default_iteration_definition'),
        ('temporal_lobe', '0005_iterationshiftparticipantstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='current_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='temporal_lobe.iterationshift'),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporal_lobe.iterationdefinition'),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environments.projectenvironment'),
        ),
    ]
