# Generated by Django 6.0.2 on 2026-02-28 19:36

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central_nervous_system', '0001_initial'),
        ('frontal_lobe', '0001_initial'),
        ('prefrontal_cortex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalosEngramTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalosEngram',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('heads', models.ManyToManyField(blank=True, related_name='engrams', to='central_nervous_system.hydrahead')),
                ('sessions', models.ManyToManyField(blank=True, related_name='engrams', to='frontal_lobe.reasoningsession')),
                ('source_turns', models.ManyToManyField(blank=True, related_name='engrams', to='frontal_lobe.reasoningturn')),
                ('tasks', models.ManyToManyField(blank=True, related_name='engrams', to='prefrontal_cortex.pfctask')),
                ('tags', models.ManyToManyField(blank=True, related_name='engrams', to='hippocampus.talosengramtag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
