# Generated by Django 6.0.2 on 2026-03-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hippocampus', '0001_initial'),
        ('prefrontal_cortex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talosengram',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='prefrontal_cortex.pfctask'),
        ),
        migrations.AddField(
            model_name='talosengram',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='hippocampus.talosengramtag'),
        ),
    ]
