# Generated by Django 6.0.2 on 2026-02-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hippocampus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talosengram',
            old_name='heads',
            new_name='spikes',
        ),
    ]
