# Generated by Django 6.0.2 on 2026-03-23 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central_nervous_system', '0002_initial'),
        ('frontal_lobe', '0002_initial'),
        ('hippocampus', '0001_initial'),
        ('identity', '0001_initial'),
        ('prefrontal_cortex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talosengram',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engrams_creator', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='talosengram',
            name='identity_discs',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='talosengram',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='frontal_lobe.reasoningsession'),
        ),
        migrations.AddField(
            model_name='talosengram',
            name='source_turns',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='frontal_lobe.reasoningturn'),
        ),
        migrations.AddField(
            model_name='talosengram',
            name='spikes',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='central_nervous_system.spike'),
        ),
        migrations.AddField(
            model_name='talosengram',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='prefrontal_cortex.pfctask'),
        ),
        migrations.AddField(
            model_name='talosengram',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='hippocampus.talosengramtag'),
        ),
    ]
