# Generated by Django 6.0.2 on 2026-02-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hippocampus', '0002_alter_talosengram_heads_alter_talosengram_sessions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TalosEngram',
        ),
    ]
