# Generated by Django 6.0.2 on 2026-03-13 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippocampus', '0002_initial'),
        ('identity', '0004_rename_ai_models_identity_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talosengram',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engrams_creator', to='identity.identitydisc'),
        ),
        migrations.AddField(
            model_name='talosengram',
            name='identity_discs',
            field=models.ManyToManyField(blank=True, related_name='engrams', to='identity.identitydisc'),
        ),
    ]
