# Generated by Django 6.0.4 on 2026-04-12 03:22

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippocampus', '0002_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEngram',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('body', models.TextField()),
                ('yaml_frontmatter', models.JSONField(blank=True, default=dict)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('identity_disc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_engrams', to='identity.identitydisc')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillFileAttachment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('script', 'Script'), ('template', 'Template'), ('reference', 'Reference'), ('asset', 'Asset')], max_length=16)),
                ('file_path', models.CharField(max_length=512)),
                ('file_content', models.TextField(blank=True, default='')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='hippocampus.skillengram')),
            ],
            options={
                'ordering': ['file_type', 'file_path'],
                'unique_together': {('skill', 'file_path')},
            },
        ),
    ]
