# Generated by Django 6.0.2 on 2026-02-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hippocampus', '0004_talosengram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talosengram',
            name='vector_id',
        ),
    ]
