# Generated by Django 6.0.2 on 2026-02-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontal_lobe', '0004_remove_toolcall_status_remove_toolcall_tool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('is_async', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Parameter Type',
                'verbose_name_plural': 'Parameter Types',
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('arguments', models.TextField(help_text='JSON payload of arguments.')),
                ('result_payload', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='', help_text='Error details if the tool crashed.')),
                ('call_id', models.CharField(blank=True, help_text='The unique ID generated by the LLM for this specific call.', max_length=255)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='frontal_lobe.reasoningturn')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talos_parietal.tooldefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('required', models.BooleanField(default=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='talos_parietal.tooldefinition')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='talos_parietal.toolparametertype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tool', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ParameterEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('value', models.CharField(max_length=254)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_values', to='talos_parietal.toolparameter')),
            ],
            options={
                'ordering': ['value'],
                'unique_together': {('parameter', 'value')},
            },
        ),
    ]
