# Generated by Django 6.0.2 on 2026-03-09 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('is_async', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Parameter Type',
                'verbose_name_plural': 'Parameter Types',
            },
        ),
        migrations.CreateModel(
            name='ToolUseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('focus_modifier', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('arguments', models.TextField(help_text='JSON payload of arguments.')),
                ('result_payload', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='', help_text='Error details if the tool crashed.')),
                ('call_id', models.CharField(blank=True, help_text='The unique ID generated by the LLM for this specific call.', max_length=255)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontal_lobe.reasoningstatus')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='frontal_lobe.reasoningturn')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parietal_lobe.tooldefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='parietal_lobe.toolparametertype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parietal_lobe.toolusetype'),
        ),
        migrations.CreateModel(
            name='ParameterEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('value', models.CharField(max_length=254)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_values', to='parietal_lobe.toolparameter')),
            ],
            options={
                'ordering': ['value'],
                'unique_together': {('parameter', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ToolParameterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('required', models.BooleanField(default=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_assignments', to='parietal_lobe.toolparameter')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='parietal_lobe.tooldefinition')),
            ],
            options={
                'ordering': ['tool', 'parameter__name'],
                'unique_together': {('tool', 'parameter')},
            },
        ),
    ]
