# Generated by Django 6.0.2 on 2026-02-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parietal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toolparameter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='toolparameter',
            name='required',
        ),
        migrations.RemoveField(
            model_name='toolparameter',
            name='tool',
        ),
        migrations.CreateModel(
            name='ToolParameterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('required', models.BooleanField(default=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_assignments', to='parietal_lobe.toolparameter')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='parietal_lobe.tooldefinition')),
            ],
            options={
                'ordering': ['tool', 'parameter__name'],
                'unique_together': {('tool', 'parameter')},
            },
        ),
    ]
