# Generated by Django 6.0.2 on 2026-03-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parietal_lobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolparameterassignment',
            name='prune_after_turns',
            field=models.IntegerField(default=0, help_text='If set, this parameter is replaced with [PRUNED] in the LLM context window after N turns.'),
        ),
    ]
