# Generated by Django 6.0.3 on 2026-04-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parietal_lobe', '0002_tooldefinition_genome_toolparameter_genome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolcall',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parietal_lobe.tooldefinition'),
        ),
    ]
