# Generated by Django 6.0.2 on 2026-02-18 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parietal_lobe', '0002_alter_toolparameter_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterenum',
            name='name',
        ),
    ]
