# Generated by Django 6.0.2 on 2026-02-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parietal_lobe', '0003_remove_parameterenum_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolparameterassignment',
            name='name',
        ),
    ]
