# Generated by Django 6.0.3 on 2026-04-26 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroplasticity', '0004_stamp_canonical_genome'),
        ('parietal_lobe', '0003_alter_toolcall_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterenum',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AddField(
            model_name='toolparameterassignment',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AlterField(
            model_name='tooldefinition',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
        migrations.AlterField(
            model_name='toolparameter',
            name='genome',
            field=models.ForeignKey(default=uuid.UUID('1206f5a1-7ffd-4cb2-8c5a-3a9dfb5e5340'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='neuroplasticity.neuralmodifier'),
        ),
    ]
